-- create tables

create table BOOKS (
    id           number generated by default on null as identity
                 constraint books_id_pk primary key,
    NAME         varchar2(4000 char),
    AUTHOR       varchar2(4000 char),
    AVAILABLE    varchar2(4000 char) default on null 'Y' not null
);



-- Generated by Radicle QuickSQL development 20/04/2026, 15:16:23

/*
BOOKS  
    NAME
    AUTHOR
    AVAILABLE /NN /default Y






 Non-default options:
# settings = {"pk":"identityDataType"}

*/
