-- create tables

create table team_members (
    id          number generated by default on null as identity
                constraint team_members_id_pk primary key,
    username    varchar2(4000 char)
);



create table projects (
    id              number generated by default on null as identity
                    constraint projects_id_pk primary key,
    project_lead    number                    constraint projects_project_lead_fk
                    references team_members on delete cascade not null,
    name            varchar2(255 char)
);

-- table index
create index projects_i1 on projects (project_lead);



-- load data

insert into projects (
    id,
    project_lead,
    name
) values (
    1,
    97,
    'Grace Dennis'
);
insert into projects (
    id,
    project_lead,
    name
) values (
    2,
    75,
    'Elnora Payne'
);

commit;

alter table projects
modify id generated always  as identity restart start with 3;


-- Generated by Radicle QuickSQL development 20/04/2026, 15:16:23

/*
team_members
   username
projects /insert 2
   name
   project_lead /nn /references team_members /cascade






 Non-default options:
# settings = {"pk":"identityDataType"}

*/
