-- create tables

create table data_feed_vectors (
    e1              vector(10240,*,*),
    EMBED_VECTOR    vector(*,*,*),
    EMBED           vector(*,*,*),
    E2              vector(12,*,*)
);



-- Generated by Radicle QuickSQL development 20/04/2026, 15:16:23

/*
data_feed_vectors
    e1  vect10k
    EMBED_VECTOR vect
    EMBED vector
    E2  vector123    
  



 Non-default options:
# settings = {"genpk":false}

*/
