-- create tables

create table "日本語" (
    id        number default on null to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') 
              constraint "日本語_id_pk" primary key,
    status    integer constraint "日本語_status_ck"
              check (status in (1,2,3))
);



-- Generated by Quick SQL development 16/04/2026, 01:08:50

/*
日本語
  id /pk
  status int /check 1,2,3





 Non-default options:
# settings = {"genpk":false}

*/
