-- create tables

create table departments (
    id          number generated by default on null as identity
                constraint departments_id_pk primary key,
    name        varchar2(255 char),
    location    varchar2(255 char),
    country     varchar2(255 char)
);


create table employees (
    id               number generated by default on null as identity
                     constraint employees_id_pk primary key,
    department_id    number                     constraint employees_department_id_fk
                     references departments,
    name             varchar2(255 char),
    email            varchar2(255 char),
    job              varchar2(255 char),
    hiredate         date
);

-- table index
create index employees_i1 on employees (department_id);



begin
    ords.enable_object(p_enabled=>TRUE, p_object=>'DEPARTMENTS');
end;
/

begin
    ords.enable_object(p_enabled=>TRUE, p_object=>'EMPLOYEES');
end;
/

-- Generated by Quick SQL development 20/04/2026, 15:16:02

/*
departments /rest
   name
   location vc255
   country vc255
   employees /rest
      name
      email
      job vc255
      hiredate






 Non-default options:
# settings = {"pk":"identityDataType"}

*/
