-- create tables

create sequence  departments_seq;

create table departments (
    id    number default on null departments_seq.nextval 
          constraint departments_id_pk primary key
);



-- Generated by Quick SQL development 16/04/2026, 01:08:49

/*
departments




 Non-default options:
# settings = {"pk":"SEQ"}

*/
