-- create tables

create table departments (
    id          number generated by default on null as identity
                constraint departments_id_pk primary key,
    name        varchar2(255 char) not null,
    location    varchar2(4000 char),
    country     varchar2(4000 char)
);


create table employees (
    id               number generated by default on null as identity
                     constraint employees_id_pk primary key,
    department_id    number                     constraint employees_department_id_fk
                     references departments,
    name             varchar2(50 char) not null,
    email            varchar2(255 char),
    cost_center      number,
    date_hired       date,
    job              varchar2(255 char)
);

-- table index
create index employees_i1 on employees (department_id);




-- triggers
create or replace editionable trigger employees_bi
    before insert
    on employees
    for each row
begin
    :new.email := lower(:new.email);
end employees_bi;
/

create or replace editionable trigger employees_bu
    before update
    on employees
    for each row
begin
    :new.email := lower(:new.email);
end employees_bu;
/


-- create views
create or replace view emp_v as
select
    departments.id           department_id,
    departments.name         department_name,
    departments.location     location,
    departments.country      country,
    employees.id             employee_id,
    employees.name           employee_name,
    employees.email          email,
    employees.cost_center    cost_center,
    employees.date_hired     date_hired,
    employees.job            job
from
    departments
    left join employees
        on employees.department_id = departments.id
/

-- load data

insert into departments (
    id,
    name,
    location,
    country
) values (
    1,
    'Manufacturing',
    'Covdiiku',
    'VE'
);
insert into departments (
    id,
    name,
    location,
    country
) values (
    2,
    'Manufacturing',
    'Honunuh',
    'TW'
);

commit;

alter table departments
modify id generated always  as identity restart start with 3;

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    1,
    2,
    'Mark Taylor',
    'zu@ro.gov',
    7,
    sysdate-96,
    'Consultant'
);
insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    2,
    1,
    'Seth Holmes',
    'pok@zavig.cy',
    21,
    sysdate-58,
    'Engineer'
);
insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    3,
    2,
    'Joseph Boone',
    'likuswuj@oh.mq',
    82,
    sysdate-21,
    'Specialist'
);
insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    4,
    1,
    'Clifford Lee',
    'ofosid@daej.mo',
    1,
    sysdate-88,
    'Manager'
);

commit;

alter table employees
modify id generated always  as identity restart start with 5;


-- Generated by Quick SQL development 20/04/2026, 15:16:02

/*
departments /insert 2
   name /nn
   location
   country
   employees /insert 4
      name /nn vc50
      email /lower
      cost center num
      date hired
      job vc255
view emp_v departments employees







 Non-default options:
# settings = {"apex":true,"db":"23c","editionable":true,"pk":"identityDataType"}

*/
