-- create tables

create table departments (
    id            number generated by default on null as identity
                  constraint departments_id_pk primary key,
    name          varchar2(255 char),
    location      varchar2(255 char),
    country       varchar2(255 char),
    created       date not null,
    created_by    varchar2(255 char) not null,
    updated       date not null,
    updated_by    varchar2(255 char) not null
);


create table employees (
    id               number generated by default on null as identity
                     constraint employees_id_pk primary key,
    department_id    number                     constraint employees_department_id_fk
                     references departments,
    name             varchar2(255 char),
    email            varchar2(255 char),
    job              varchar2(255 char),
    hiredate         date,
    created          date not null,
    created_by       varchar2(255 char) not null,
    updated          date not null,
    updated_by       varchar2(255 char) not null
);

-- table index
create index employees_i1 on employees (department_id);



-- triggers
create or replace trigger departments_bi
    before insert
    on departments
    for each row
begin
    :new.created := sysdate;
    :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end departments_bi;
/

create or replace trigger departments_bu
    before update
    on departments
    for each row
begin
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end departments_bu;
/


create or replace trigger employees_bi
    before insert
    on employees
    for each row
begin
    :new.created := sysdate;
    :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end employees_bi;
/

create or replace trigger employees_bu
    before update
    on employees
    for each row
begin
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end employees_bu;
/


-- Generated by Quick SQL development 16/04/2026, 01:08:41

/*
departments
   name
   location vc255
   country vc255
   employees
      name
      email
      job vc255
      hiredate






 Non-default options:
# settings = {"apex":true,"auditcols":true,"db":"12c","pk":"identityDataType"}

*/
