-- create tables

create table dept (
    id            number generated by default on null as identity
                  constraint dept_id_pk primary key,
    name          varchar2(255 char),
    created_on    date
);



-- Generated by Radicle QuickSQL development 20/04/2026, 15:16:03

/*
dept
    name
    created_on






 Non-default options:
# settings = {"pk":"identityDataType"}

*/
