-- create tables

create table customers (
    cust_id             number generated by default on null as identity
                   constraint customers_cust_id_pk primary key,
    cust_name      varchar2(255 char),
    cust_email     varchar2(255 char),
    cust_phone1    varchar2(4000 char),
    cust_phone2    varchar2(4000 char)
);



-- Generated by Quick SQL development 16/04/2026, 01:08:48

/*
customers /colprefix cust
  name
  email
  phone1
  phone2






 Non-default options:
# settings = {"pk":"identityDataType"}

*/
