-- create tables

create table products (
    id      number generated by default on null as identity
            constraint products_id_pk primary key,
    name    varchar2(255 char)
);



create table customers (
    id            number generated by default on null as identity
                  constraint customers_id_pk primary key,
    first_name    varchar2(4000 char)
);



create table channels (
    id      number generated by default on null as identity
            constraint channels_id_pk primary key,
    name    varchar2(255 char)
);



create table promotions (
    id      number generated by default on null as identity
            constraint promotions_id_pk primary key,
    name    varchar2(255 char)
);



create table sales (
    id              number generated by default on null as identity
                    constraint sales_id_pk primary key,
    product_id      number                    constraint sales_product_id_fk
                    references products,
    customer_id     number                    constraint sales_customer_id_fk
                    references customers,
    promotion_id    number                    constraint sales_promotion_id_fk
                    references promotions,
    channel_id      number                    constraint sales_channel_id_fk
                    references channels
);

-- table index
create index sales_i1 on sales (product_id);

create index sales_i2 on sales (customer_id);

create index sales_i3 on sales (promotion_id);

create index sales_i4 on sales (channel_id);



-- Generated by Quick SQL development 16/04/2026, 01:08:49

/*
products
   name
customers
   first name
channels
   name
promotions
   name
sales
   product_id
   customer_id
   promotion id
   channel id






 Non-default options:
# settings = {"pk":"identityDataType"}

*/
