create sequence  row_key_seq;

-- create tables

create table departments (
    id          number generated by default on null as identity
                constraint departments_id_pk primary key,
    row_key     varchar2(30 char)
                constraint departments_row_key_unq unique not null,
    name        varchar2(255 char) not null,
    location    varchar2(4000 char),
    country     varchar2(4000 char)
);


create table employees (
    id               number generated by default on null as identity
                     constraint employees_id_pk primary key,
    department_id    number                     constraint employees_department_id_fk
                     references departments,
    row_key          varchar2(30 char)
                     constraint employees_row_key_unq unique not null,
    name             varchar2(50 char) not null,
    email            varchar2(255 char),
    cost_center      number,
    date_hired       date,
    job              varchar2(255 char)
);

-- table index
create index employees_i1 on employees (department_id);



-- triggers
create or replace trigger departments_bi
    before insert
    on departments
    for each row
declare
    function compress_int (n in integer ) return varchar2
    as
        ret       varchar2(30);
        quotient  integer;
        remainder integer;
        digit     char(1);
    begin
        ret := null; quotient := n;
        <<compress_loop>>
        while quotient > 0
        loop
            remainder := mod(quotient, 10 + 26);
            quotient := floor(quotient  / (10 + 26));
            if remainder < 26 then
                digit := chr(ascii('A') + remainder);
            else
                digit := chr(ascii('0') + remainder - 26);
            end if;
            ret := digit || ret;
        end loop compress_loop;
        if length(ret) < 5 then ret := lpad(ret, 4, 'A'); end if ;
        return upper(ret);
    end compress_int;
begin
    :new.row_key := compress_int(row_key_seq.nextval);
end departments_bi;
/


create or replace trigger employees_bi
    before insert
    on employees
    for each row
declare
    function compress_int (n in integer ) return varchar2
    as
        ret       varchar2(30);
        quotient  integer;
        remainder integer;
        digit     char(1);
    begin
        ret := null; quotient := n;
        <<compress_loop>>
        while quotient > 0
        loop
            remainder := mod(quotient, 10 + 26);
            quotient := floor(quotient  / (10 + 26));
            if remainder < 26 then
                digit := chr(ascii('A') + remainder);
            else
                digit := chr(ascii('0') + remainder - 26);
            end if;
            ret := digit || ret;
        end loop compress_loop;
        if length(ret) < 5 then ret := lpad(ret, 4, 'A'); end if ;
        return upper(ret);
    end compress_int;
begin
    :new.row_key := compress_int(row_key_seq.nextval);
    :new.email := lower(:new.email);
end employees_bi;
/

create or replace trigger employees_bu
    before update
    on employees
    for each row
begin
    :new.email := lower(:new.email);
end employees_bu;
/


-- load data

insert into departments (
    id,
    name,
    location,
    country
) values (
    1,
    'Manufacturing',
    'Covdiiku',
    'VE'
);
insert into departments (
    id,
    name,
    location,
    country
) values (
    2,
    'Manufacturing',
    'Honunuh',
    'TW'
);

commit;

alter table departments
modify id generated always  as identity restart start with 3;

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    1,
    2,
    'Mark Taylor',
    'zu@ro.gov',
    7,
    sysdate-96,
    'Consultant'
);
insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    2,
    1,
    'Seth Holmes',
    'pok@zavig.cy',
    21,
    sysdate-58,
    'Engineer'
);
insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    3,
    2,
    'Joseph Boone',
    'likuswuj@oh.mq',
    82,
    sysdate-21,
    'Specialist'
);
insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    4,
    1,
    'Clifford Lee',
    'ofosid@daej.mo',
    1,
    sysdate-88,
    'Manager'
);

commit;

alter table employees
modify id generated always  as identity restart start with 5;


-- Generated by Quick SQL development 16/04/2026, 01:08:41

/*


departments /insert 2
   name /nn
   location
   country
   employees /insert 4
      name /nn vc50
      email /lower
      cost center num
      date hired
      job vc255






 Non-default options:
# settings = {"pk":"identityDataType","rowkey":true}

*/
