-- create tables

create table dept (
    id       number generated by default on null as identity
             constraint dept_id_pk primary key,
    name     varchar2(255 char),
    city     varchar2(4000 char),
    state    varchar2(4000 char)
);

alter table dept add constraint dept_uk unique (name,email);


create table emp (
    id         number generated by default on null as identity
               constraint emp_id_pk primary key,
    dept_id    number               constraint emp_dept_id_fk
               references dept,
    name       varchar2(255 char),
    email      varchar2(255 char)
);

-- table index
create index emp_i1 on emp (dept_id);

alter table emp add constraint emp_uk unique (name,email);



-- Generated by Quick SQL development 16/04/2026, 01:08:48

/*
dept  /unique name, email /insert 0
    name
    city 
    state
    emp /unique name, email
        name
        email 






 Non-default options:
# settings = {"pk":"identityDataType"}

*/
