-- create tables

create table departments (
    id       number generated by default on null as identity
             constraint departments_id_pk primary key,
    dname    varchar2(4000 char)
);


create table emp (
    id               number generated by default on null as identity
                     constraint emp_id_pk primary key,
    department_id    number                     constraint emp_department_id_fk
                     references departments on delete cascade,
    ename            varchar2(4000 char)
);

-- table index
create index emp_i1 on emp (department_id);



-- Generated by Quick SQL development 16/04/2026, 01:08:49

/*
departments
    dname
    emp  /cascade
        department_id /fk departments 
        ename






 Non-default options:
# settings = {"pk":"identityDataType"}

*/
