-- create tables

create table departments (
    id          number generated by default on null as identity
                constraint departments_id_pk primary key,
    name        varchar2(255 char) not null,
    location    varchar2(4000 char),
    country     varchar2(4000 char)
);


create table employees (
    id               number generated by default on null as identity
                     constraint employees_id_pk primary key,
    department_id    number                     constraint employees_department_id_fk
                     references departments,
    name             varchar2(50 char) not null,
    email            varchar2(255 char),
    cost_center      number
);

-- table index
create index employees_i1 on employees (department_id);



-- triggers
create or replace trigger employees_bi
    before insert
    on employees
    for each row
begin
    :new.email := lower(:new.email);
end employees_bi;
/

create or replace trigger employees_bu
    before update
    on employees
    for each row
begin
    :new.email := lower(:new.email);
end employees_bu;
/


-- APIs
create or replace package departments_api
is

    procedure get_row (
        p_id        in  number,
        p_name   out  varchar2,
        p_location   out  varchar2,
        p_country   out  varchar2
    );

    procedure insert_row (
        p_id        in  number default null,
        p_name    in  varchar2 default null,
        p_location    in  varchar2 default null,
        p_country    in  varchar2 default null
    );

    procedure update_row (
        p_id        in  number default null,
        p_name    in  varchar2 default null,
        p_location    in  varchar2 default null,
        p_country    in  varchar2 default null
    );

    procedure delete_row (
        p_id              in number
    );
end departments_api;
/

create or replace package body departments_api
is

    procedure get_row (
        p_id        in  number,
        p_name   out  varchar2,
        p_location   out  varchar2,
        p_country   out  varchar2
    )
    is 
    begin 
        select name,
               location,
               country
          into p_name,
               p_location,
               p_country
          from departments
         where id = p_id;
    exception
        when no_data_found then
            null;
    end get_row;
 
    procedure insert_row (
        p_id        in  number default null,
        p_name    in  varchar2 default null,
        p_location    in  varchar2 default null,
        p_country    in  varchar2 default null
    )
    is 
    begin 
        insert into departments ( 
            id,
            name,
            location,
            country
        ) values ( 
            p_id,
            p_name,
            p_location,
            p_country
        );
    end insert_row;
 
     procedure update_row (
        p_id        in  number default null,
        p_name    in  varchar2 default null,
        p_location    in  varchar2 default null,
        p_country    in  varchar2 default null
    )
    is 
    begin 
        update  departments set 
            id = p_id,
            name = p_name,
            location = p_location,
            country = p_country
        where id = p_id;
    end update_row;
 
     procedure delete_row (
        p_id              in number
    )
    is
    begin
        delete from departments where id = p_id;
    end delete_row;
end departments_api;
/

create or replace package employees_api
is

    procedure get_row (
        p_id        in  number,
        p_department_id   out  number,
        p_name   out  varchar2,
        p_email   out  varchar2,
        p_cost_center   out  number
    );

    procedure insert_row (
        p_id        in  number default null,
        p_department_id    in  number default null,
        p_name    in  varchar2 default null,
        p_email    in  varchar2 default null,
        p_cost_center    in  number default null
    );

    procedure update_row (
        p_id        in  number default null,
        p_department_id    in  number default null,
        p_name    in  varchar2 default null,
        p_email    in  varchar2 default null,
        p_cost_center    in  number default null
    );

    procedure delete_row (
        p_id              in number
    );
end employees_api;
/

create or replace package body employees_api
is

    procedure get_row (
        p_id        in  number,
        p_department_id   out  number,
        p_name   out  varchar2,
        p_email   out  varchar2,
        p_cost_center   out  number
    )
    is 
    begin 
        select department_id,
               name,
               email,
               cost_center
          into p_department_id,
               p_name,
               p_email,
               p_cost_center
          from employees
         where id = p_id;
    exception
        when no_data_found then
            null;
    end get_row;
 
    procedure insert_row (
        p_id        in  number default null,
        p_department_id    in  number default null,
        p_name    in  varchar2 default null,
        p_email    in  varchar2 default null,
        p_cost_center    in  number default null
    )
    is 
    begin 
        insert into employees ( 
            id,
            department_id,
            name,
            email,
            cost_center
        ) values ( 
            p_id,
            p_department_id,
            p_name,
            p_email,
            p_cost_center
        );
    end insert_row;
 
     procedure update_row (
        p_id        in  number default null,
        p_department_id    in  number default null,
        p_name    in  varchar2 default null,
        p_email    in  varchar2 default null,
        p_cost_center    in  number default null
    )
    is 
    begin 
        update  employees set 
            id = p_id,
            department_id = p_department_id,
            name = p_name,
            email = p_email,
            cost_center = p_cost_center
        where id = p_id;
    end update_row;
 
     procedure delete_row (
        p_id              in number
    )
    is
    begin
        delete from employees where id = p_id;
    end delete_row;
end employees_api;
/

-- Generated by Quick SQL development 16/04/2026, 01:08:41

/*
departments /api
   name /nn
   location
   country
   employees /api
      name /nn vc50
      email /lower
      cost center num






 Non-default options:
# settings = {"pk":"identityDataType"}

*/
