-- create tables

create table customers (
    id      number generated by default on null as identity
            constraint customers_id_pk primary key,
    name    varchar2(255 char)
);



create table products (
    id       number generated by default on null as identity
             constraint products_id_pk primary key,
    name     varchar2(255 char),
    price    number
);



create table warehouses (
    id      number generated by default on null as identity
            constraint warehouses_id_pk primary key,
    name    varchar2(255 char)
);



create table orders (
    id             number generated by default on null as identity
                   constraint orders_id_pk primary key,
    customer_id    number                   constraint orders_customer_id_fk
                   references customers on delete cascade,
    order_date     date
);

-- table index
create index orders_i1 on orders (customer_id);



create table order_lines (
    id            number generated by default on null as identity
                  constraint order_lines_id_pk primary key,
    product_id    number                  constraint order_lines_product_id_fk
                  references products on delete cascade,
    quantity      number
);

-- table index
create index order_lines_i1 on order_lines (product_id);



create table line_fulfillments (
    id              number generated by default on null as identity
                    constraint line_fulfillments_id_pk primary key,
    warehouse_id    number                    constraint line_fulfillments_warehouse_id_fk
                    references warehouses,
    line_id         number                    constraint line_fulfillments_line_id_fk
                    references order_lines on delete cascade
);

-- table index
create index line_fulfillments_i1 on line_fulfillments (warehouse_id);

create index line_fulfillments_i2 on line_fulfillments (line_id);



-- Generated by Radicle QuickSQL development 20/04/2026, 15:16:01

/*
customers
    name

products
    name
    price num

warehouses
    name

orders
    order_date
    customer_id /fk /cascade customers

order_lines
    quantity num
    product_id /fk products /cascade

line_fulfillments
    warehouse_id /fk warehouses
    line_id /cascade /fk order_lines






 Non-default options:
# settings = {"pk":"identityDataType"}

*/
