
-- create tables

create table abc_emp (
    id        number generated by default on null as identity
              constraint abc_emp_id_pk primary key,
    deptno    number,
    ename     varchar2(4000 char)
)
annotations (TGROUP "Employee Group");

-- table index
create index abc_emp_i1 on abc_emp (deptno);



create table abc_dept (
    id       number generated by default on null as identity
             constraint abc_dept_id_pk primary key,
    dname    varchar2(4000 char)
);



create table abc_user (
    id             number generated by default on null as identity
                   constraint abc_user_id_pk primary key,
    username       varchar2(4000 char) annotations (DESCRIPTION "Username column"),
    description    clob annotations (DESCRIPTION "Description column")
)
annotations (DESCRIPTION "User table");

comment on table abc_user is 'User table';
comment on column abc_user.username is 'Username column';
comment on column abc_user.description is 'Description column';


alter table abc_emp add constraint abc_emp_deptno_fk foreign key (deptno) references abc_dept;

-- translation support

create table abc_language (
    code           varchar2(5 char) not null
                   constraint abc_language_code_pk primary key,
    locale         varchar2(28 char) not null
                   constraint abc_language_locale_unq unique,
    name           varchar2(1024 char),
    native_name    varchar2(1024 char)
);

create index abc_language_i1 on abc_language (locale);

create table abc_dept_trans (
    id               number generated by default on null as identity
                     constraint abc_dept_trans_id_pk primary key,
    dept_id          number not null,
    language_code    varchar2(5 char) not null,
    trans_dname      varchar2(4000 char),
    constraint abc_dept_trans_uk unique (dept_id, language_code)
);

alter table abc_dept_trans add constraint abc_dept_trans_de_id_fk
    foreign key (dept_id) references abc_dept;

alter table abc_dept_trans add constraint abc_dept_trans_lang_fk
    foreign key (language_code) references abc_language (code);

create index abc_dept_trans_i1 on abc_dept_trans (dept_id);
create index abc_dept_trans_i2 on abc_dept_trans (language_code);

create table abc_user_trans (
    id                   number generated by default on null as identity
                         constraint abc_user_trans_id_pk primary key,
    user_id              number not null,
    language_code        varchar2(5 char) not null,
    trans_username       varchar2(4000 char),
    trans_description    clob,
    constraint abc_user_trans_uk unique (user_id, language_code)
);

alter table abc_user_trans add constraint abc_user_trans_us_id_fk
    foreign key (user_id) references abc_user;

alter table abc_user_trans add constraint abc_user_trans_lang_fk
    foreign key (language_code) references abc_language (code);

create index abc_user_trans_i1 on abc_user_trans (user_id);
create index abc_user_trans_i2 on abc_user_trans (language_code);

-- immutable triggers
create or replace trigger trg_abc_dept_insertonly
    before update or delete
    on abc_dept
declare
    co_immutable_err  constant pls_integer      := -20055;
    co_immutable_msg  constant varchar2(200 char) := 'abc_dept is immutable';
begin
    raise_application_error(co_immutable_err, co_immutable_msg);
end;
/

-- create views
create or replace view abc_dept_resolved as
select k.id,
         coalesce(t.trans_dname, k.dname) as dname
from abc_dept k
left join abc_dept_trans t
    on t.dept_id = k.id
    and t.language_code = sys_context('APP_CTX','LANG');

create or replace view abc_user_resolved as
select k.id,
         coalesce(t.trans_username, k.username) as username,
         coalesce(t.trans_description, k.description) as description
from abc_user k
left join abc_user_trans t
    on t.user_id = k.id
    and t.language_code = sys_context('APP_CTX','LANG');

-- table groups
insert into user_annotations_groups$ (group_name) values ('Employee Group');
insert into user_annotations_group_members$ (group_name, object_name) values ('Employee Group', 'ABC_EMP');

-- Generated by Radicle QuickSQL

/*
emp {TGROUP "Employee Group"}
  ename
  deptno /fk dept

dept /immutable
  dname /trans

user {DESCRIPTION "User table"}
  username /trans {
    DESCRIPTION "Username column"
  }
  description clob /trans {
    DESCRIPTION "Description column"
  }

 Non-default options:
# settings = {"prefix":"abc","pk":"identityDataType"}

*/
