-- create tables

create table bug35756025 (
    deptno    number,
    dname     varchar2(14 char),
    loc       varchar2(13 char)
);



-- Generated by Quick SQL development 16/04/2026, 01:08:55

/*
-- TEST 1 (genpk off)
bug35756025
    deptno num
    dname vc14
    loc   vc13





 Non-default options:
# settings = {"genpk":"N"}

*/
