-- create tables

create table bug35756025 (
    deptno    number generated by default on null as identity
              constraint bug35756025_deptno_pk primary key,
    dname     varchar2(14 char),
    loc       varchar2(13 char)
);



-- Generated by Quick SQL development 20/04/2026, 15:16:09

/*
bug35756025
    deptno num /nn /pk
    dname vc14
    loc   vc13






 Non-default options:
# settings = {"pk":"identityDataType"}

*/
