-- create tables

create table bug35756025 (
    deptno    number not null
              constraint bug35756025_deptno_pk primary key,
    dname     varchar2(14 char),
    loc       varchar2(13 char)
);



-- Generated by Quick SQL development 16/04/2026, 01:08:55

/*
bug35756025
    deptno num /nn /pk
    dname vc14
    loc   vc13





 Non-default options:
# settings = {"pk":"none"}

*/
