drop table employees cascade constraints;
drop package employees_api;
drop table timecards cascade constraints;
drop package timecards_api;
drop view employee_timecards;
-- create tables

create table employees (
    id               number generated by default on null as identity
                     constraint employees_id_pk primary key,
    name             varchar2(255 char)
                     constraint employees_name_unq unique not null,
    email            varchar2(255 char)
                     constraint employees_email_unq unique not null,
    country          varchar2(100 char) not null,
    employee_type    varchar2(30 char) constraint employees_employee_type_ck
                     check (employee_type in ('full time','part time')),
    approver         varchar2(255 char) not null,
    row_version      integer not null
);

-- table index
create index employees_i1 on employees (approver);

create table timecards (
    id                       number generated by default on null as identity
                             constraint timecards_id_pk primary key,
    employee_id              number                             constraint timecards_employee_id_fk
                             references employees,
    status                   varchar2(4000 char) default on null 'SUBMITTED' constraint timecards_status_ck
                             check (status in ('SUBMITTED','APPROVED','DECLINED')),
    week_of                  date not null,
    sunday                   integer default on null 0 constraint timecards_sunday_bet
           check (sunday between 0 and 24),
    monday                   integer default on null 0 constraint timecards_monday_bet
           check (monday between 0 and 24),
    tuesday                  integer default on null 0 constraint timecards_tuesday_bet
           check (tuesday between 0 and 24),
    wednesday                integer default on null 0 constraint timecards_wednesday_bet
           check (wednesday between 0 and 24),
    thursday                 integer default on null 0 constraint timecards_thursday_bet
           check (thursday between 0 and 24),
    friday                   integer default on null 0 constraint timecards_friday_bet
           check (friday between 0 and 24),
    saturday                 integer default on null 0 constraint timecards_saturday_bet
           check (saturday between 0 and 24),
    comments                 varchar2(4000 char),
    confirmation_code_v50    varchar2(4000 char),
    row_version              integer not null,
    created                  date not null,
    created_by               varchar2(255 char) not null,
    updated                  date not null,
    updated_by               varchar2(255 char) not null
);

-- table index
create index timecards_i1 on timecards (employee_id);




-- triggers
create or replace trigger employees_bi
    before insert
    on employees
    for each row
begin
    :new.email := lower(:new.email);
    :new.row_version := 1;
end employees_bi;
/

create or replace trigger employees_bu
    before update
    on employees
    for each row
begin
    :new.email := lower(:new.email);
    :new.row_version := nvl(:old.row_version, 0) + 1;
end employees_bu;
/


create or replace trigger timecards_bi
    before insert
    on timecards
    for each row
begin
    :new.row_version := 1;
    :new.created := sysdate;
    :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end timecards_bi;
/

create or replace trigger timecards_bu
    before update
    on timecards
    for each row
begin
    :new.row_version := nvl(:old.row_version, 0) + 1;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end timecards_bu;
/


-- APIs
create or replace package employees_api
is

    procedure get_row (
        p_id        in  integer,
        p_name   out  varchar2,
        p_email   out  varchar2,
        p_country   out  varchar2,
        p_employee_type   out  varchar2,
        p_approver   out  varchar2
    );

    procedure insert_row (
        p_id        in  integer default null,
        p_name    in  varchar2 default null,
        p_email    in  varchar2 default null,
        p_country    in  varchar2 default null,
        p_employee_type    in  varchar2 default null,
        p_approver    in  varchar2 default null
    );

    procedure update_row (
        p_id        in  integer default null,
        p_name    in  varchar2 default null,
        p_email    in  varchar2 default null,
        p_country    in  varchar2 default null,
        p_employee_type    in  varchar2 default null,
        p_approver    in  varchar2 default null
    );

    procedure delete_row (
        p_id              in integer
    );
end employees_api;
/

create or replace package body employees_api
is

    procedure get_row (
        p_id        in  integer,
        p_name   out  varchar2,
        p_email   out  varchar2,
        p_country   out  varchar2,
        p_employee_type   out  varchar2,
        p_approver   out  varchar2
    )
    is 
    begin 
        select name,
               email,
               country,
               employee_type,
               approver
          into p_name,
               p_email,
               p_country,
               p_employee_type,
               p_approver
          from employees
         where id = p_id;
    exception
        when no_data_found then
            null;
    end get_row;
 
    procedure insert_row (
        p_id        in  integer default null,
        p_name    in  varchar2 default null,
        p_email    in  varchar2 default null,
        p_country    in  varchar2 default null,
        p_employee_type    in  varchar2 default null,
        p_approver    in  varchar2 default null
    )
    is 
    begin 
        insert into employees ( 
            id,
            name,
            email,
            country,
            employee_type,
            approver
        ) values ( 
            p_id,
            p_name,
            p_email,
            p_country,
            p_employee_type,
            p_approver
        );
    end insert_row;
 
     procedure update_row (
        p_id        in  integer default null,
        p_name    in  varchar2 default null,
        p_email    in  varchar2 default null,
        p_country    in  varchar2 default null,
        p_employee_type    in  varchar2 default null,
        p_approver    in  varchar2 default null
    )
    is 
    begin 
        update  employees set 
            id = p_id,
            name = p_name,
            email = p_email,
            country = p_country,
            employee_type = p_employee_type,
            approver = p_approver
        where id = p_id;
    end update_row;
 
     procedure delete_row (
        p_id              in integer
    )
    is
    begin
        delete from employees where id = p_id;
    end delete_row;
end employees_api;
/

create or replace package timecards_api
is

    procedure get_row (
        p_id        in  integer,
        p_employee_id   out  integer,
        p_status   out  varchar2,
        p_week_of   out  date,
        p_sunday   out  integer,
        p_monday   out  integer,
        p_tuesday   out  integer,
        p_wednesday   out  integer,
        p_thursday   out  integer,
        p_friday   out  integer,
        p_saturday   out  integer,
        p_comments   out  varchar2,
        p_confirmation_code_v50   out  varchar2
    );

    procedure insert_row (
        p_id        in  integer default null,
        p_employee_id    in  integer default null,
        p_status    in  varchar2 default null,
        p_week_of    in  date default null,
        p_sunday    in  integer default null,
        p_monday    in  integer default null,
        p_tuesday    in  integer default null,
        p_wednesday    in  integer default null,
        p_thursday    in  integer default null,
        p_friday    in  integer default null,
        p_saturday    in  integer default null,
        p_comments    in  varchar2 default null,
        p_confirmation_code_v50    in  varchar2 default null
    );

    procedure update_row (
        p_id        in  integer default null,
        p_employee_id    in  integer default null,
        p_status    in  varchar2 default null,
        p_week_of    in  date default null,
        p_sunday    in  integer default null,
        p_monday    in  integer default null,
        p_tuesday    in  integer default null,
        p_wednesday    in  integer default null,
        p_thursday    in  integer default null,
        p_friday    in  integer default null,
        p_saturday    in  integer default null,
        p_comments    in  varchar2 default null,
        p_confirmation_code_v50    in  varchar2 default null
    );

    procedure delete_row (
        p_id              in integer
    );
end timecards_api;
/

create or replace package body timecards_api
is

    procedure get_row (
        p_id        in  integer,
        p_employee_id   out  integer,
        p_status   out  varchar2,
        p_week_of   out  date,
        p_sunday   out  integer,
        p_monday   out  integer,
        p_tuesday   out  integer,
        p_wednesday   out  integer,
        p_thursday   out  integer,
        p_friday   out  integer,
        p_saturday   out  integer,
        p_comments   out  varchar2,
        p_confirmation_code_v50   out  varchar2
    )
    is 
    begin 
        select employee_id,
               status,
               week_of,
               sunday,
               monday,
               tuesday,
               wednesday,
               thursday,
               friday,
               saturday,
               comments,
               confirmation_code_v50
          into p_employee_id,
               p_status,
               p_week_of,
               p_sunday,
               p_monday,
               p_tuesday,
               p_wednesday,
               p_thursday,
               p_friday,
               p_saturday,
               p_comments,
               p_confirmation_code_v50
          from timecards
         where id = p_id;
    exception
        when no_data_found then
            null;
    end get_row;
 
    procedure insert_row (
        p_id        in  integer default null,
        p_employee_id    in  integer default null,
        p_status    in  varchar2 default null,
        p_week_of    in  date default null,
        p_sunday    in  integer default null,
        p_monday    in  integer default null,
        p_tuesday    in  integer default null,
        p_wednesday    in  integer default null,
        p_thursday    in  integer default null,
        p_friday    in  integer default null,
        p_saturday    in  integer default null,
        p_comments    in  varchar2 default null,
        p_confirmation_code_v50    in  varchar2 default null
    )
    is 
    begin 
        insert into timecards ( 
            id,
            employee_id,
            status,
            week_of,
            sunday,
            monday,
            tuesday,
            wednesday,
            thursday,
            friday,
            saturday,
            comments,
            confirmation_code_v50
        ) values ( 
            p_id,
            p_employee_id,
            p_status,
            p_week_of,
            p_sunday,
            p_monday,
            p_tuesday,
            p_wednesday,
            p_thursday,
            p_friday,
            p_saturday,
            p_comments,
            p_confirmation_code_v50
        );
    end insert_row;
 
     procedure update_row (
        p_id        in  integer default null,
        p_employee_id    in  integer default null,
        p_status    in  varchar2 default null,
        p_week_of    in  date default null,
        p_sunday    in  integer default null,
        p_monday    in  integer default null,
        p_tuesday    in  integer default null,
        p_wednesday    in  integer default null,
        p_thursday    in  integer default null,
        p_friday    in  integer default null,
        p_saturday    in  integer default null,
        p_comments    in  varchar2 default null,
        p_confirmation_code_v50    in  varchar2 default null
    )
    is 
    begin 
        update  timecards set 
            id = p_id,
            employee_id = p_employee_id,
            status = p_status,
            week_of = p_week_of,
            sunday = p_sunday,
            monday = p_monday,
            tuesday = p_tuesday,
            wednesday = p_wednesday,
            thursday = p_thursday,
            friday = p_friday,
            saturday = p_saturday,
            comments = p_comments,
            confirmation_code_v50 = p_confirmation_code_v50
        where id = p_id;
    end update_row;
 
     procedure delete_row (
        p_id              in integer
    )
    is
    begin
        delete from timecards where id = p_id;
    end delete_row;
end timecards_api;
/

-- create views
create or replace view employee_timecards as
select
    employees.id                       employee_id,
    employees.name                     name,
    employees.email                    email,
    employees.country                  country,
    employees.employee_type            employee_type,
    employees.approver                 approver,
    employees.row_version      employee_row_version,
    timecards.id                       timecard_id,
    timecards.status                   status,
    timecards.week_of                  week_of,
    timecards.sunday                   sunday,
    timecards.monday                   monday,
    timecards.tuesday                  tuesday,
    timecards.wednesday                wednesday,
    timecards.thursday                 thursday,
    timecards.friday                   friday,
    timecards.saturday                 saturday,
    timecards.comments                 comments,
    timecards.confirmation_code_v50    confirmation_code_v50,
    timecards.row_version              timecard_row_version,
    timecards.created                  timecard_created,
    timecards.created_by               timecard_created_by,
    timecards.updated                  timecard_updated,
    timecards.updated_by               timecard_updated_by
from
    employees
    left join timecards
        on timecards.employee_id = employees.id
/

-- load data

insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    1,
    'Landon Glover',
    'buoki@kawo.bh',
    'Mexico',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    2,
    'Philip Brewer',
    'binotse@wo.dz',
    'US',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    3,
    'Patrick Herrera',
    'pihaw@zamuneb.ws',
    'Canada',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    4,
    'Mina Lambert',
    'pes@duche.qa',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    5,
    'Shane Harvey',
    'zi@ti.gov',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    6,
    'Clifford Lee',
    'ofosid@daej.mo',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    7,
    'Cody Wells',
    'hate@fu.ve',
    'US',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    8,
    'Jesus Gibson',
    'nulcun@gelet.cr',
    'Mexico',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    9,
    'Mario Martin',
    'fe@veig.tz',
    'Mexico',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    10,
    'Elsie Curtis',
    'aw@kivuwip.be',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    11,
    'Carlos Wagner',
    'te@zoluzu.al',
    'Mexico',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    12,
    'Bobby Tucker',
    'faz@map.ec',
    'Canada',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    13,
    'Francis Cain',
    'safopid@ke.pk',
    'Canada',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    14,
    'Eugene Pierce',
    'oli@dutuza.sz',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    15,
    'Lillian Baker',
    'et@pabejgi.mm',
    'Canada',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    16,
    'Alvin Wallace',
    'wig@hitungef.mm',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    17,
    'Mildred Mason',
    'kem@ziovedu.zw',
    'Mexico',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    18,
    'Barbara Phillips',
    'wehovuce@guhin.gt',
    'Canada',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    19,
    'Larry Johnson',
    'tohhij@ujaez.gy',
    'Canada',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    20,
    'Jay Terry',
    'turuhu@tog.mn',
    'US',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    21,
    'Louise Carroll',
    'zev@domisuje.fj',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    22,
    'Mattie Logan',
    'ha@pen.net',
    'Canada',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    23,
    'Cynthia Conner',
    'benom@uniicucuc.gw',
    'Canada',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    24,
    'Leon Fleming',
    'vegub@tidewe.ve',
    'Mexico',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    25,
    'Jeremy Sharp',
    'wupikdoh@ror.io',
    'US',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    26,
    'Rodney Strickland',
    'jo@ukjihdak.sk',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    27,
    'Hester Arnold',
    'ju@papaetu.lr',
    'Canada',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    28,
    'John Malone',
    'fopav@jesekga.nf',
    'Mexico',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    29,
    'Adrian Soto',
    'kaarobu@zeku.cd',
    'US',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    30,
    'Logan Pittman',
    'ha@unewivtel.lr',
    'Mexico',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    31,
    'Violet Chambers',
    'cipicka@tudsafi.va',
    'Canada',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    32,
    'Clara Cobb',
    'je@taore.mh',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    33,
    'Rose Maxwell',
    've@wobedu.mw',
    'Canada',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    34,
    'Nellie Santos',
    'bog@roisude.kr',
    'Canada',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    35,
    'Wayne Hill',
    'sid@ombe.ve',
    'US',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    36,
    'Jesse Turner',
    'maeh@duc.gu',
    'Canada',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    37,
    'Sarah Davidson',
    'jis@meci.vn',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    38,
    'Estella Allen',
    'suafide@avnubik.jm',
    'Canada',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    39,
    'Todd Alvarado',
    'ope@juab.zw',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    40,
    'Joe Graves',
    'siganuezo@zu.uy',
    'Mexico',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    41,
    'Bernice Nelson',
    'fogfa@suf.gn',
    'Canada',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    42,
    'Lucy Austin',
    'geobi@ocdobta.md',
    'Mexico',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    43,
    'Pauline Bennett',
    'ru@nirfe.ba',
    'US',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    44,
    'Ronnie Bowen',
    'bufni@vajoke.io',
    'Canada',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    45,
    'Alejandro Crawford',
    'rojurcin@penbubezi.no',
    'US',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    46,
    'Jesse Tate',
    'pos@nagoded.bb',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    47,
    'Florence Willis',
    'juvku@el.cn',
    'US',
    'part time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    48,
    'Ralph Byrd',
    'coet@za.cc',
    'US',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    49,
    'Jack Diaz',
    'nitdopuz@dibles.ml',
    'Mexico',
    'full time',
    'tbd'
);
insert into employees (
    id,
    name,
    email,
    country,
    employee_type,
    approver
) values (
    50,
    'Jacob Peterson',
    'rico@sobhepkun.sm',
    'Canada',
    'part time',
    'tbd'
);

commit;

alter table employees
modify id generated always  as identity restart start with 51;

insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    1,
    29,
    'APPROVED',
    sysdate-48,
    0,
    13,
    2,
    21,
    6,
    3,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    2,
    46,
    'SUBMITTED',
    sysdate-41,
    16,
    11,
    22,
    10,
    7,
    17,
    17,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    3,
    37,
    'SUBMITTED',
    sysdate-20,
    1,
    11,
    8,
    10,
    22,
    18,
    16,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    4,
    34,
    'APPROVED',
    sysdate-64,
    3,
    22,
    20,
    20,
    4,
    21,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    5,
    50,
    'APPROVED',
    sysdate-43,
    7,
    19,
    13,
    5,
    4,
    6,
    4,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    6,
    23,
    'APPROVED',
    sysdate-34,
    18,
    5,
    15,
    18,
    4,
    9,
    17,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    7,
    4,
    'DECLINED',
    sysdate-55,
    3,
    15,
    3,
    3,
    3,
    15,
    0,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    8,
    5,
    'SUBMITTED',
    sysdate-48,
    18,
    15,
    8,
    17,
    16,
    9,
    3,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    9,
    41,
    'APPROVED',
    sysdate-37,
    15,
    20,
    14,
    5,
    20,
    1,
    20,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    10,
    14,
    'SUBMITTED',
    sysdate-36,
    20,
    0,
    13,
    15,
    13,
    4,
    12,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    11,
    35,
    'APPROVED',
    sysdate-56,
    4,
    11,
    13,
    22,
    24,
    5,
    13,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    12,
    29,
    'SUBMITTED',
    sysdate-15,
    17,
    16,
    7,
    2,
    15,
    5,
    21,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    13,
    12,
    'APPROVED',
    sysdate-36,
    20,
    0,
    22,
    19,
    6,
    11,
    0,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    14,
    14,
    'APPROVED',
    sysdate-41,
    5,
    15,
    0,
    15,
    23,
    8,
    15,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    15,
    8,
    'APPROVED',
    sysdate-52,
    17,
    22,
    11,
    24,
    11,
    19,
    19,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    16,
    5,
    'SUBMITTED',
    sysdate-17,
    14,
    8,
    3,
    16,
    18,
    17,
    11,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    17,
    16,
    'APPROVED',
    sysdate-49,
    22,
    24,
    7,
    16,
    16,
    14,
    6,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    18,
    40,
    'APPROVED',
    sysdate-16,
    0,
    6,
    9,
    1,
    12,
    23,
    19,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    19,
    50,
    'APPROVED',
    sysdate-97,
    7,
    4,
    0,
    14,
    15,
    15,
    1,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    20,
    34,
    'SUBMITTED',
    sysdate-95,
    2,
    1,
    5,
    3,
    14,
    24,
    24,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    21,
    22,
    'SUBMITTED',
    sysdate-43,
    15,
    16,
    15,
    20,
    9,
    5,
    1,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    22,
    1,
    'SUBMITTED',
    sysdate-62,
    17,
    5,
    16,
    8,
    17,
    15,
    7,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    23,
    31,
    'SUBMITTED',
    sysdate-54,
    15,
    17,
    3,
    16,
    12,
    13,
    3,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    24,
    34,
    'DECLINED',
    sysdate-27,
    0,
    1,
    5,
    22,
    9,
    7,
    12,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    25,
    48,
    'DECLINED',
    sysdate-92,
    21,
    14,
    11,
    22,
    22,
    23,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    26,
    4,
    'DECLINED',
    sysdate-51,
    10,
    5,
    14,
    8,
    9,
    2,
    8,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    27,
    40,
    'APPROVED',
    sysdate-5,
    1,
    20,
    10,
    2,
    15,
    5,
    15,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    28,
    8,
    'DECLINED',
    sysdate-82,
    8,
    14,
    12,
    13,
    23,
    24,
    20,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    29,
    44,
    'SUBMITTED',
    sysdate-56,
    21,
    2,
    0,
    4,
    12,
    2,
    5,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    30,
    31,
    'SUBMITTED',
    sysdate-54,
    24,
    24,
    20,
    22,
    6,
    4,
    10,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    31,
    26,
    'SUBMITTED',
    sysdate-54,
    22,
    16,
    17,
    20,
    2,
    6,
    12,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    32,
    44,
    'DECLINED',
    sysdate-64,
    18,
    4,
    24,
    4,
    9,
    10,
    21,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    33,
    20,
    'DECLINED',
    sysdate-82,
    23,
    4,
    3,
    16,
    16,
    21,
    0,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    34,
    15,
    'APPROVED',
    sysdate-87,
    16,
    2,
    20,
    11,
    8,
    13,
    15,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    35,
    11,
    'DECLINED',
    sysdate-83,
    17,
    12,
    15,
    12,
    22,
    5,
    21,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    36,
    35,
    'APPROVED',
    sysdate-23,
    4,
    3,
    11,
    2,
    10,
    5,
    15,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    37,
    5,
    'SUBMITTED',
    sysdate-27,
    22,
    24,
    20,
    16,
    17,
    4,
    13,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    38,
    23,
    'DECLINED',
    sysdate-22,
    5,
    9,
    17,
    13,
    7,
    17,
    5,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    39,
    14,
    'DECLINED',
    sysdate-36,
    17,
    14,
    4,
    9,
    15,
    19,
    5,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    40,
    40,
    'SUBMITTED',
    sysdate-10,
    6,
    0,
    22,
    21,
    9,
    1,
    4,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    41,
    42,
    'DECLINED',
    sysdate-68,
    22,
    12,
    5,
    3,
    6,
    21,
    18,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    42,
    47,
    'DECLINED',
    sysdate-8,
    1,
    14,
    0,
    15,
    21,
    17,
    10,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    43,
    27,
    'DECLINED',
    sysdate-77,
    14,
    4,
    18,
    1,
    11,
    15,
    3,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    44,
    22,
    'DECLINED',
    sysdate-71,
    14,
    19,
    10,
    16,
    5,
    10,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    45,
    16,
    'SUBMITTED',
    sysdate-52,
    5,
    11,
    4,
    0,
    10,
    19,
    7,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    46,
    35,
    'DECLINED',
    sysdate-89,
    3,
    16,
    10,
    18,
    18,
    2,
    2,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    47,
    17,
    'SUBMITTED',
    sysdate-22,
    9,
    17,
    10,
    1,
    2,
    12,
    21,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    48,
    38,
    'APPROVED',
    sysdate-17,
    8,
    4,
    9,
    7,
    4,
    19,
    1,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    49,
    48,
    'SUBMITTED',
    sysdate-42,
    14,
    16,
    16,
    4,
    9,
    9,
    15,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    50,
    37,
    'DECLINED',
    sysdate-38,
    24,
    3,
    1,
    2,
    22,
    13,
    14,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    51,
    2,
    'DECLINED',
    sysdate-92,
    16,
    3,
    1,
    20,
    19,
    13,
    1,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    52,
    15,
    'DECLINED',
    sysdate-78,
    1,
    0,
    22,
    10,
    24,
    4,
    17,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    53,
    9,
    'DECLINED',
    sysdate-36,
    14,
    19,
    20,
    1,
    12,
    24,
    17,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    54,
    16,
    'APPROVED',
    sysdate-18,
    2,
    14,
    11,
    6,
    17,
    0,
    14,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    55,
    5,
    'DECLINED',
    sysdate-95,
    10,
    7,
    5,
    13,
    2,
    21,
    17,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    56,
    31,
    'APPROVED',
    sysdate-20,
    2,
    1,
    10,
    3,
    0,
    7,
    16,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    57,
    37,
    'SUBMITTED',
    sysdate-94,
    5,
    6,
    19,
    9,
    0,
    16,
    14,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    58,
    9,
    'SUBMITTED',
    sysdate-54,
    5,
    8,
    13,
    19,
    10,
    13,
    12,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    59,
    28,
    'APPROVED',
    sysdate-53,
    3,
    6,
    19,
    4,
    24,
    14,
    9,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    60,
    21,
    'DECLINED',
    sysdate-99,
    1,
    20,
    9,
    24,
    15,
    12,
    16,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    61,
    50,
    'SUBMITTED',
    sysdate-89,
    24,
    6,
    9,
    18,
    6,
    0,
    0,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    62,
    5,
    'APPROVED',
    sysdate-45,
    24,
    21,
    21,
    20,
    11,
    19,
    12,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    63,
    7,
    'APPROVED',
    sysdate-99,
    19,
    14,
    23,
    14,
    24,
    8,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    64,
    35,
    'APPROVED',
    sysdate-5,
    7,
    3,
    4,
    12,
    17,
    15,
    1,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    65,
    1,
    'APPROVED',
    sysdate-29,
    17,
    17,
    11,
    6,
    7,
    3,
    1,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    66,
    9,
    'SUBMITTED',
    sysdate-66,
    16,
    15,
    16,
    11,
    6,
    1,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    67,
    11,
    'DECLINED',
    sysdate-82,
    0,
    22,
    21,
    24,
    7,
    3,
    17,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    68,
    43,
    'SUBMITTED',
    sysdate-47,
    3,
    24,
    24,
    10,
    8,
    12,
    11,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    69,
    7,
    'DECLINED',
    sysdate-98,
    21,
    17,
    9,
    11,
    0,
    15,
    11,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    70,
    31,
    'APPROVED',
    sysdate-74,
    12,
    5,
    2,
    23,
    2,
    20,
    10,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    71,
    44,
    'APPROVED',
    sysdate-31,
    19,
    15,
    12,
    16,
    12,
    22,
    5,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    72,
    36,
    'APPROVED',
    sysdate-32,
    5,
    5,
    24,
    20,
    7,
    12,
    18,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    73,
    1,
    'SUBMITTED',
    sysdate-7,
    17,
    11,
    0,
    9,
    12,
    1,
    9,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    74,
    4,
    'APPROVED',
    sysdate-91,
    18,
    11,
    13,
    19,
    4,
    21,
    0,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    75,
    30,
    'APPROVED',
    sysdate-70,
    7,
    1,
    7,
    4,
    6,
    17,
    3,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    76,
    1,
    'SUBMITTED',
    sysdate-68,
    10,
    6,
    5,
    13,
    2,
    7,
    12,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    77,
    10,
    'DECLINED',
    sysdate-98,
    18,
    7,
    24,
    19,
    7,
    24,
    10,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    78,
    13,
    'DECLINED',
    sysdate-93,
    0,
    15,
    14,
    12,
    6,
    24,
    8,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    79,
    35,
    'APPROVED',
    sysdate-5,
    12,
    21,
    14,
    5,
    22,
    0,
    16,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    80,
    31,
    'SUBMITTED',
    sysdate-75,
    23,
    10,
    0,
    21,
    11,
    5,
    14,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    81,
    44,
    'DECLINED',
    sysdate-85,
    20,
    14,
    14,
    24,
    15,
    3,
    6,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    82,
    45,
    'APPROVED',
    sysdate-9,
    0,
    16,
    1,
    0,
    2,
    6,
    23,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    83,
    17,
    'APPROVED',
    sysdate-87,
    19,
    8,
    3,
    4,
    7,
    18,
    8,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    84,
    7,
    'SUBMITTED',
    sysdate-51,
    10,
    19,
    15,
    1,
    7,
    24,
    3,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    85,
    22,
    'DECLINED',
    sysdate-11,
    14,
    10,
    16,
    7,
    3,
    19,
    15,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    86,
    42,
    'DECLINED',
    sysdate-32,
    24,
    9,
    1,
    16,
    12,
    2,
    17,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    87,
    8,
    'APPROVED',
    sysdate-37,
    21,
    0,
    1,
    12,
    24,
    15,
    15,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    88,
    15,
    'APPROVED',
    sysdate-59,
    8,
    4,
    6,
    14,
    19,
    14,
    10,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    89,
    1,
    'DECLINED',
    sysdate-40,
    4,
    18,
    20,
    20,
    23,
    2,
    21,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    90,
    25,
    'APPROVED',
    sysdate-50,
    8,
    2,
    5,
    8,
    14,
    14,
    18,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    91,
    38,
    'SUBMITTED',
    sysdate-10,
    6,
    3,
    7,
    14,
    3,
    22,
    16,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    92,
    50,
    'DECLINED',
    sysdate-63,
    1,
    11,
    17,
    15,
    22,
    1,
    24,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    93,
    46,
    'DECLINED',
    sysdate-76,
    12,
    7,
    14,
    21,
    9,
    22,
    3,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    94,
    36,
    'SUBMITTED',
    sysdate-11,
    9,
    22,
    15,
    8,
    18,
    20,
    2,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    95,
    1,
    'SUBMITTED',
    sysdate-82,
    20,
    24,
    5,
    5,
    3,
    21,
    21,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    96,
    26,
    'SUBMITTED',
    sysdate-97,
    0,
    13,
    24,
    22,
    10,
    3,
    4,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    97,
    38,
    'SUBMITTED',
    sysdate-80,
    20,
    7,
    10,
    10,
    17,
    6,
    8,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    98,
    16,
    'SUBMITTED',
    sysdate-3,
    7,
    21,
    12,
    20,
    1,
    24,
    23,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    99,
    32,
    'SUBMITTED',
    sysdate-8,
    2,
    22,
    19,
    17,
    19,
    13,
    24,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    100,
    19,
    'DECLINED',
    sysdate-88,
    23,
    14,
    21,
    23,
    16,
    16,
    14,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    101,
    44,
    'DECLINED',
    sysdate-63,
    14,
    4,
    23,
    9,
    16,
    19,
    21,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    102,
    44,
    'SUBMITTED',
    sysdate-30,
    4,
    13,
    19,
    5,
    22,
    4,
    17,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    103,
    8,
    'DECLINED',
    sysdate-42,
    16,
    11,
    0,
    15,
    3,
    22,
    21,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    104,
    13,
    'DECLINED',
    sysdate-35,
    20,
    13,
    19,
    13,
    15,
    13,
    12,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    105,
    4,
    'APPROVED',
    sysdate-25,
    6,
    15,
    11,
    3,
    18,
    17,
    15,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    106,
    46,
    'SUBMITTED',
    sysdate-61,
    7,
    7,
    12,
    22,
    15,
    23,
    23,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    107,
    21,
    'DECLINED',
    sysdate-39,
    4,
    5,
    19,
    7,
    10,
    16,
    18,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    108,
    26,
    'DECLINED',
    sysdate-5,
    21,
    20,
    2,
    24,
    11,
    14,
    9,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    109,
    43,
    'DECLINED',
    sysdate-57,
    22,
    2,
    13,
    0,
    14,
    20,
    5,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    110,
    28,
    'DECLINED',
    sysdate-50,
    10,
    3,
    17,
    24,
    6,
    21,
    4,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    111,
    42,
    'DECLINED',
    sysdate-44,
    5,
    10,
    12,
    12,
    5,
    2,
    4,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    112,
    29,
    'SUBMITTED',
    sysdate-19,
    0,
    20,
    12,
    21,
    22,
    9,
    21,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    113,
    42,
    'DECLINED',
    sysdate-9,
    22,
    22,
    9,
    23,
    1,
    9,
    7,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    114,
    11,
    'SUBMITTED',
    sysdate-81,
    9,
    23,
    10,
    13,
    2,
    1,
    20,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    115,
    17,
    'DECLINED',
    sysdate-88,
    3,
    9,
    21,
    3,
    20,
    5,
    15,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    116,
    11,
    'APPROVED',
    sysdate-42,
    6,
    23,
    20,
    8,
    12,
    3,
    23,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    117,
    23,
    'APPROVED',
    sysdate-28,
    11,
    24,
    5,
    12,
    21,
    24,
    3,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    118,
    50,
    'SUBMITTED',
    sysdate-40,
    9,
    21,
    0,
    4,
    6,
    11,
    18,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    119,
    16,
    'SUBMITTED',
    sysdate-68,
    6,
    9,
    11,
    5,
    20,
    22,
    13,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    120,
    9,
    'APPROVED',
    sysdate-71,
    15,
    4,
    1,
    7,
    21,
    23,
    2,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    121,
    8,
    'SUBMITTED',
    sysdate-69,
    13,
    19,
    6,
    1,
    2,
    19,
    23,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    122,
    4,
    'DECLINED',
    sysdate-24,
    18,
    2,
    7,
    3,
    19,
    13,
    20,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    123,
    44,
    'SUBMITTED',
    sysdate-72,
    13,
    23,
    16,
    20,
    0,
    9,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    124,
    7,
    'DECLINED',
    sysdate-67,
    7,
    6,
    7,
    7,
    3,
    4,
    3,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    125,
    36,
    'DECLINED',
    sysdate-76,
    5,
    15,
    3,
    7,
    17,
    7,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    126,
    7,
    'DECLINED',
    sysdate-62,
    7,
    6,
    8,
    22,
    15,
    1,
    7,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    127,
    1,
    'APPROVED',
    sysdate-13,
    21,
    2,
    13,
    23,
    13,
    24,
    11,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    128,
    26,
    'SUBMITTED',
    sysdate-45,
    0,
    24,
    22,
    3,
    3,
    21,
    2,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    129,
    43,
    'APPROVED',
    sysdate-44,
    19,
    18,
    0,
    14,
    5,
    22,
    20,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    130,
    29,
    'DECLINED',
    sysdate-54,
    3,
    3,
    18,
    10,
    21,
    20,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    131,
    30,
    'SUBMITTED',
    sysdate-19,
    21,
    21,
    12,
    14,
    21,
    12,
    0,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    132,
    16,
    'DECLINED',
    sysdate-79,
    19,
    10,
    19,
    8,
    17,
    20,
    19,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    133,
    17,
    'APPROVED',
    sysdate-94,
    12,
    9,
    0,
    6,
    8,
    14,
    11,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    134,
    43,
    'DECLINED',
    sysdate-78,
    2,
    5,
    10,
    17,
    14,
    12,
    13,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    135,
    25,
    'DECLINED',
    sysdate-83,
    5,
    15,
    2,
    9,
    5,
    16,
    15,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    136,
    22,
    'SUBMITTED',
    sysdate-85,
    17,
    2,
    21,
    3,
    2,
    9,
    12,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    137,
    39,
    'DECLINED',
    sysdate-14,
    8,
    6,
    17,
    24,
    1,
    1,
    19,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    138,
    11,
    'APPROVED',
    sysdate-13,
    10,
    2,
    10,
    14,
    4,
    18,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    139,
    27,
    'SUBMITTED',
    sysdate-14,
    19,
    6,
    20,
    14,
    3,
    14,
    0,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    140,
    20,
    'APPROVED',
    sysdate-48,
    12,
    8,
    1,
    1,
    13,
    14,
    5,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    141,
    16,
    'SUBMITTED',
    sysdate-56,
    4,
    19,
    3,
    21,
    6,
    24,
    15,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    142,
    41,
    'SUBMITTED',
    sysdate-5,
    23,
    13,
    23,
    19,
    17,
    24,
    4,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    143,
    3,
    'APPROVED',
    sysdate-51,
    21,
    18,
    7,
    20,
    21,
    21,
    20,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    144,
    46,
    'DECLINED',
    sysdate-11,
    1,
    20,
    11,
    5,
    10,
    12,
    4,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    145,
    38,
    'SUBMITTED',
    sysdate-4,
    8,
    11,
    8,
    13,
    7,
    16,
    3,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    146,
    26,
    'DECLINED',
    sysdate-66,
    20,
    12,
    5,
    14,
    2,
    0,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    147,
    27,
    'APPROVED',
    sysdate-80,
    10,
    18,
    24,
    0,
    0,
    12,
    13,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    148,
    1,
    'APPROVED',
    sysdate-85,
    20,
    18,
    13,
    22,
    23,
    7,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    149,
    41,
    'SUBMITTED',
    sysdate-19,
    3,
    4,
    0,
    23,
    12,
    20,
    13,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    150,
    18,
    'DECLINED',
    sysdate-44,
    20,
    6,
    20,
    24,
    24,
    1,
    8,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    151,
    15,
    'DECLINED',
    sysdate-47,
    0,
    7,
    10,
    1,
    1,
    2,
    4,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    152,
    9,
    'SUBMITTED',
    sysdate-43,
    20,
    20,
    2,
    23,
    3,
    15,
    11,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    153,
    19,
    'DECLINED',
    sysdate-48,
    22,
    12,
    2,
    7,
    15,
    20,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    154,
    11,
    'DECLINED',
    sysdate-19,
    20,
    9,
    6,
    3,
    20,
    24,
    24,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    155,
    9,
    'APPROVED',
    sysdate-90,
    5,
    13,
    13,
    6,
    19,
    11,
    9,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    156,
    29,
    'APPROVED',
    sysdate-82,
    20,
    24,
    24,
    22,
    4,
    1,
    6,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    157,
    2,
    'SUBMITTED',
    sysdate-61,
    10,
    19,
    24,
    24,
    23,
    19,
    17,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    158,
    29,
    'DECLINED',
    sysdate-44,
    3,
    15,
    22,
    4,
    18,
    4,
    24,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    159,
    5,
    'DECLINED',
    sysdate-61,
    0,
    20,
    9,
    6,
    15,
    4,
    5,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    160,
    26,
    'SUBMITTED',
    sysdate-75,
    24,
    20,
    0,
    24,
    24,
    9,
    18,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    161,
    26,
    'SUBMITTED',
    sysdate-35,
    21,
    22,
    11,
    22,
    14,
    6,
    5,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    162,
    18,
    'DECLINED',
    sysdate-4,
    16,
    17,
    18,
    16,
    22,
    19,
    8,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    163,
    39,
    'DECLINED',
    sysdate-11,
    12,
    13,
    18,
    20,
    5,
    21,
    10,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    164,
    25,
    'DECLINED',
    sysdate-48,
    7,
    24,
    5,
    14,
    0,
    24,
    13,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    165,
    10,
    'APPROVED',
    sysdate-14,
    12,
    2,
    22,
    2,
    6,
    9,
    21,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    166,
    1,
    'SUBMITTED',
    sysdate-83,
    15,
    15,
    10,
    9,
    15,
    16,
    21,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    167,
    23,
    'DECLINED',
    sysdate-32,
    2,
    18,
    21,
    11,
    18,
    7,
    22,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    168,
    49,
    'APPROVED',
    sysdate-61,
    22,
    12,
    21,
    6,
    5,
    6,
    16,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    169,
    16,
    'SUBMITTED',
    sysdate-75,
    8,
    14,
    12,
    12,
    23,
    21,
    18,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    170,
    48,
    'DECLINED',
    sysdate-6,
    22,
    9,
    22,
    5,
    6,
    23,
    3,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    171,
    35,
    'SUBMITTED',
    sysdate-57,
    3,
    11,
    15,
    16,
    21,
    7,
    4,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    172,
    26,
    'SUBMITTED',
    sysdate-63,
    23,
    13,
    17,
    22,
    13,
    6,
    8,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    173,
    11,
    'APPROVED',
    sysdate-63,
    8,
    1,
    13,
    23,
    17,
    1,
    2,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    174,
    49,
    'DECLINED',
    sysdate-44,
    3,
    17,
    1,
    11,
    2,
    1,
    9,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    175,
    47,
    'DECLINED',
    sysdate-26,
    19,
    12,
    4,
    21,
    10,
    18,
    6,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    176,
    16,
    'DECLINED',
    sysdate-68,
    8,
    20,
    15,
    15,
    18,
    8,
    20,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    177,
    12,
    'SUBMITTED',
    sysdate-71,
    13,
    15,
    19,
    8,
    16,
    9,
    13,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    178,
    12,
    'SUBMITTED',
    sysdate-66,
    1,
    1,
    23,
    9,
    2,
    5,
    12,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    179,
    17,
    'DECLINED',
    sysdate-62,
    7,
    11,
    17,
    24,
    14,
    23,
    19,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    180,
    30,
    'DECLINED',
    sysdate-79,
    18,
    1,
    22,
    14,
    14,
    13,
    3,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    181,
    9,
    'DECLINED',
    sysdate-25,
    20,
    12,
    17,
    20,
    10,
    3,
    9,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    182,
    24,
    'DECLINED',
    sysdate-57,
    2,
    8,
    18,
    23,
    17,
    3,
    24,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    183,
    46,
    'APPROVED',
    sysdate-88,
    17,
    22,
    2,
    21,
    2,
    2,
    18,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    184,
    27,
    'APPROVED',
    sysdate-8,
    16,
    14,
    9,
    24,
    12,
    10,
    9,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    185,
    18,
    'APPROVED',
    sysdate-29,
    15,
    9,
    6,
    19,
    23,
    9,
    9,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    186,
    40,
    'SUBMITTED',
    sysdate-81,
    1,
    24,
    9,
    3,
    4,
    20,
    20,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    187,
    46,
    'SUBMITTED',
    sysdate-95,
    16,
    15,
    5,
    23,
    15,
    20,
    9,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    188,
    6,
    'DECLINED',
    sysdate-11,
    18,
    20,
    0,
    6,
    8,
    23,
    18,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    189,
    25,
    'DECLINED',
    sysdate-92,
    20,
    10,
    0,
    12,
    7,
    19,
    14,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    190,
    29,
    'DECLINED',
    sysdate-70,
    9,
    2,
    20,
    24,
    0,
    0,
    9,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    191,
    29,
    'SUBMITTED',
    sysdate-86,
    10,
    7,
    23,
    21,
    6,
    23,
    0,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    192,
    44,
    'DECLINED',
    sysdate-99,
    9,
    19,
    18,
    1,
    1,
    8,
    17,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    193,
    16,
    'DECLINED',
    sysdate-36,
    16,
    22,
    13,
    19,
    15,
    18,
    19,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    194,
    30,
    'DECLINED',
    sysdate-72,
    7,
    16,
    23,
    23,
    6,
    0,
    9,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    195,
    17,
    'SUBMITTED',
    sysdate-16,
    7,
    9,
    9,
    15,
    0,
    3,
    5,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    196,
    21,
    'SUBMITTED',
    sysdate-34,
    16,
    17,
    15,
    3,
    1,
    0,
    8,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    197,
    5,
    'DECLINED',
    sysdate-11,
    9,
    0,
    20,
    21,
    7,
    5,
    13,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    198,
    31,
    'SUBMITTED',
    sysdate-82,
    5,
    4,
    0,
    17,
    23,
    3,
    10,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    199,
    26,
    'SUBMITTED',
    sysdate-66,
    20,
    5,
    6,
    6,
    5,
    5,
    5,
    'N/A',
    null
);
insert into timecards (
    id,
    employee_id,
    status,
    week_of,
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
    comments,
    confirmation_code_v50
) values (
    200,
    17,
    'SUBMITTED',
    sysdate-49,
    16,
    21,
    23,
    6,
    13,
    16,
    13,
    'N/A',
    null
);

commit;

alter table timecards
modify id generated always  as identity restart start with 201;


-- Generated by Quick SQL development 20/04/2026, 15:15:44

/*
employees /insert 50 /api
    name /nn /unique  
    email /nn /lower /unique
    country vc100 /nn /values US, Canada, Mexico
    employee type vc30 --<--/n-->-- /check full time, part time 
    approver vc255 /nn /index /values tbd
    timecards /api /auditcols /insert 200
        status /check SUBMITTED, APPROVED, DECLINED /default SUBMITTED
        week of date /nn
        sunday int /default 0 /between 0 and 24
        monday int /default 0 /between 0 and 24
        tuesday int /default 0 /between 0 and 24
        wednesday int /default 0 /between 0 and 24
        thursday int /default 0 /between 0 and 24
        friday int /default 0 /between 0 and 24
        saturday int /default 0 /between 0 and 24
        comments
        confirmation code v50 /values null

view employee_timecards employees timecards




 Non-default options:
# settings = {"apex":true,"drop":true,"pk":"identityDataType","rowversion":true,"api":true}

*/
