-- create tables

create table assignees (
    id              number generated by default on null as identity
                    constraint assignees_id_pk primary key,
    full_name       varchar2(255 char) not null,
    email           varchar2(255 char),
    phone_number    number,
    created         date not null,
    created_by      varchar2(255 char) not null,
    updated         date not null,
    updated_by      varchar2(255 char) not null
);


create table todos (
    id             number generated by default on null as identity
                   constraint todos_id_pk primary key,
    assignee_id    number                   constraint todos_assignee_id_fk
                   references assignees,
    name           varchar2(255 char) not null,
    due_date       date,
    priority       varchar2(50 char) constraint todos_priority_ck
                   check (priority in ('P1','P2','P3')),
    status         varchar2(50 char) constraint todos_status_ck
                   check (status in ('OPEN','COMPLETE','ON HOLD','CANCELLED')),
    created        date not null,
    created_by     varchar2(255 char) not null,
    updated        date not null,
    updated_by     varchar2(255 char) not null
);

-- table index
create index todos_i1 on todos (assignee_id);



-- triggers
create or replace trigger assignees_bi
    before insert
    on assignees
    for each row
begin
    :new.created := sysdate;
    :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end assignees_bi;
/

create or replace trigger assignees_bu
    before update
    on assignees
    for each row
begin
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end assignees_bu;
/


create or replace trigger todos_bi
    before insert
    on todos
    for each row
begin
    :new.created := sysdate;
    :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end todos_bi;
/

create or replace trigger todos_bu
    before update
    on todos
    for each row
begin
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end todos_bu;
/


-- load data

insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    1,
    'Landon Glover',
    'buoki@kawo.bh',
    97
);
insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    2,
    'George Klein',
    'ketbeun@sim.ge',
    58
);
insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    3,
    'Philip Brewer',
    'binotse@wo.dz',
    27
);
insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    4,
    'Christine Marshall',
    'zovba@uf.kz',
    96
);
insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    5,
    'Patrick Herrera',
    'pihaw@zamuneb.ws',
    45
);
insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    6,
    'Seth Holmes',
    'pok@zavig.cy',
    21
);
insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    7,
    'Mina Lambert',
    'pes@duche.qa',
    5
);
insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    8,
    'Bernice Gordon',
    'lepfo@kozhonmi.bn',
    26
);
insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    9,
    'Shane Harvey',
    'zi@ti.gov',
    21
);
insert into assignees (
    id,
    full_name,
    email,
    phone_number
) values (
    10,
    'Jessie Kim',
    'ewuwip@redfecuh.sj',
    13
);

commit;

alter table assignees
modify id generated always  as identity restart start with 11;

insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    1,
    8,
    'Alex Vaughn',
    sysdate-3,
    'P3',
    'COMPLETE'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    2,
    3,
    'Jeanette White',
    sysdate-10,
    'P2',
    'ON HOLD'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    3,
    9,
    'Olga Butler',
    sysdate-55,
    'P1',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    4,
    2,
    'Leila Pratt',
    sysdate-23,
    'P2',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    5,
    8,
    'Matilda Lynch',
    sysdate-12,
    'P2',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    6,
    9,
    'Christine Silva',
    sysdate-96,
    'P2',
    'COMPLETE'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    7,
    9,
    'Francis Cain',
    sysdate-93,
    'P1',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    8,
    7,
    'Ronnie Harrington',
    sysdate-18,
    'P2',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    9,
    9,
    'Terry Mack',
    sysdate-2,
    'P3',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    10,
    10,
    'Barry Cannon',
    sysdate-90,
    'P2',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    11,
    9,
    'Jordan Howard',
    sysdate-68,
    'P3',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    12,
    8,
    'Olive Shelton',
    sysdate-78,
    'P3',
    'ON HOLD'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    13,
    3,
    'Edna Flores',
    sysdate-0,
    'P3',
    'ON HOLD'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    14,
    2,
    'Anne Hudson',
    sysdate-49,
    'P1',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    15,
    3,
    'Mattie Logan',
    sysdate-90,
    'P3',
    'ON HOLD'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    16,
    9,
    'Lula Robinson',
    sysdate-47,
    'P1',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    17,
    8,
    'Lee Barnett',
    sysdate-17,
    'P1',
    'COMPLETE'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    18,
    6,
    'Virginia Rodriquez',
    sysdate-21,
    'P1',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    19,
    3,
    'Eva Obrien',
    sysdate-94,
    'P2',
    'ON HOLD'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    20,
    3,
    'Clyde Snyder',
    sysdate-58,
    'P3',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    21,
    6,
    'Dollie Webster',
    sysdate-5,
    'P2',
    'ON HOLD'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    22,
    2,
    'Darrell Watkins',
    sysdate-16,
    'P3',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    23,
    5,
    'Violet Chambers',
    sysdate-90,
    'P3',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    24,
    4,
    'Stanley Kennedy',
    sysdate-12,
    'P3',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    25,
    4,
    'Hester Stewart',
    sysdate-18,
    'P2',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    26,
    7,
    'Bradley Tate',
    sysdate-54,
    'P2',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    27,
    2,
    'Joseph Gardner',
    sysdate-82,
    'P2',
    'ON HOLD'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    28,
    8,
    'Clyde McDonald',
    sysdate-95,
    'P2',
    'COMPLETE'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    29,
    10,
    'Virginia Payne',
    sysdate-69,
    'P1',
    'COMPLETE'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    30,
    4,
    'Oscar Tyler',
    sysdate-38,
    'P1',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    31,
    1,
    'Joe Graves',
    sysdate-33,
    'P2',
    'COMPLETE'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    32,
    1,
    'Micheal James',
    sysdate-34,
    'P3',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    33,
    2,
    'Rosa Bell',
    sysdate-78,
    'P1',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    34,
    3,
    'Keith Cain',
    sysdate-39,
    'P1',
    'COMPLETE'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    35,
    7,
    'Theodore Cain',
    sysdate-17,
    'P1',
    'ON HOLD'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    36,
    2,
    'Katherine Bryant',
    sysdate-15,
    'P3',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    37,
    10,
    'Scott Howard',
    sysdate-88,
    'P1',
    'ON HOLD'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    38,
    5,
    'Billy Flowers',
    sysdate-36,
    'P1',
    'COMPLETE'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    39,
    6,
    'Jack Diaz',
    sysdate-48,
    'P2',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    40,
    1,
    'Rebecca Herrera',
    sysdate-52,
    'P2',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    41,
    6,
    'Ian Holt',
    sysdate-45,
    'P3',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    42,
    3,
    'Daisy Zimmerman',
    sysdate-85,
    'P1',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    43,
    9,
    'Jane Quinn',
    sysdate-14,
    'P3',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    44,
    5,
    'Dennis Stevenson',
    sysdate-80,
    'P2',
    'ON HOLD'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    45,
    3,
    'Birdie Saunders',
    sysdate-70,
    'P3',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    46,
    9,
    'Birdie Osborne',
    sysdate-16,
    'P1',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    47,
    5,
    'Lewis Hudson',
    sysdate-50,
    'P1',
    'ON HOLD'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    48,
    8,
    'John McCoy',
    sysdate-51,
    'P3',
    'OPEN'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    49,
    8,
    'Joseph Stokes',
    sysdate-12,
    'P3',
    'CANCELLED'
);
insert into todos (
    id,
    assignee_id,
    name,
    due_date,
    priority,
    status
) values (
    50,
    9,
    'Lola Ingram',
    sysdate-85,
    'P1',
    'ON HOLD'
);

commit;

alter table todos
modify id generated always  as identity restart start with 51;


-- Generated by Radicle QuickSQL development 20/04/2026, 15:15:50

/*







assignees /insert 10
  full_name /nn
  email
  phone_number
  todos /insert 50 
    name vc255 /nn 
    due_date date
    priority vc50 /check P1, P2, P3
    status vc50 /check OPEN, COMPLETE, ON HOLD, CANCELLED

 Non-default options:
# settings = {"apex":true,"auditcols":true,"pk":"identityDataType"}

*/
