import { singular, concatNames, getMajorVersion } from './naming.js';
import translate from './translate.js';
import { generateSample, resetSeed } from './sample.js';
import { LexerToken } from './lexer.js';
import amend_reserved_word from './reserved_words.js';
import split_str from './split_str.js';
import { DdlNode, DEFAULT_NAMING, tab, EXPANDING_TYPES } from './node.js';
import type { DdlContext, DDLGenerator, IDdlNode, SemanticType, ErdColumn, ErdItem, ErdLink, ErdOutput } from './types.js';

// ── Local constants ───────────────────────────────────────────────────────────

type Naming = typeof DEFAULT_NAMING;

const IDENTITY_MODIFIER_LOWER = 'generated by default on null as identity';
const NOT_NULL_LOWER = ' not null';

function trimTrailingComma(s: string): string {
    if (s.lastIndexOf(',\n') === s.length - 2)
        s = s.substring(0, s.length - 2) + '\n';
    return s;
}

// ── getValue (used by _buildInsertStatement) ──────────────────────────────────

function getValue(obj: unknown, oName: string | null, attr: string, oName2Match: string): unknown[] | null {
    let ret: unknown[] = [];
    if (obj === null || obj === undefined) return null;
    if (typeof obj !== 'object') return null;
    const tmp = (obj as Record<string, unknown>)[attr];
    if (tmp !== null && tmp !== undefined && oName === oName2Match) ret.push(tmp);
    for (const p in obj as object) {
        const child = (obj as Record<string, unknown>)[p];
        const sub = getValue(child, p, attr, oName2Match);
        if (sub !== null) ret = ret.concat(sub);
    }
    return ret;
}

// ── OracleDDLGenerator ────────────────────────────────────────────────────────

export class OracleDDLGenerator implements DDLGenerator {
    private _ddl:    DdlContext;
    private _naming: Naming;

    constructor(ddlCtx: DdlContext, naming?: Naming) {
        this._ddl    = ddlCtx;
        this._naming = naming ?? DEFAULT_NAMING;
    }

    private _pkTypeModifier(objName: string, namingOverride?: Naming): string {
        const naming = namingOverride ?? this._naming;
        if (this._ddl.optionEQvalue('pk', 'identityDataType')) return IDENTITY_MODIFIER_LOWER;
        if (this._ddl.optionEQvalue('pk', 'seq'))
            return ('default on null ' + objName + naming.seq + '.NEXTVAL ').toLowerCase();
        if (this._ddl.optionEQvalue('pk', 'guid'))
            return "default on null to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') ";
        return 'not null';
    }

    /** Constraint-line prefix — aligns 'constraint' keyword under the type column. */
    private _cpad(colNode: IDdlNode): string {
        return tab + tab + ' '.repeat(colNode.parent!.maxChildNameLen());
    }

    /**
     * Resolve FK column Oracle DDL type from a referenced table's explicit PK.
     * Returns null when the referenced table uses an auto-generated PK — in that
     * case the caller should keep the FK column's own inferred type.
     */
    private _fkOracleType(refNode: IDdlNode): string | null {
        const rname = refNode.getExplicitPkName();
        if (rname === null || rname.includes(',')) return null;
        const pkChild = refNode.findChild(rname);
        return pkChild !== null ? this._toOracleType(pkChild._inferTypeFull()) : refNode.getPkType();
    }

    /**
     * Resolve FK column PL/SQL parameter type from a referenced table's explicit PK.
     * Returns null when the referenced table uses an auto-generated PK.
     */
    private _fkPlsqlType(refNode: IDdlNode): string | null {
        const rname = refNode.getExplicitPkName();
        if (rname === null || rname.includes(',')) return null;
        const pkChild = refNode.findChild(rname);
        return pkChild !== null ? pkChild.getPlsqlType() : refNode.getPkType();
    }

    /** Returns 'lower', 'upper', or '' based on node option. */
    private _caseMethod(node: IDdlNode): string {
        if (node.isOption('lower')) return 'lower';
        if (node.isOption('upper')) return 'upper';
        return '';
    }

    _toOracleType(sem: SemanticType): string {
        const s     = this._ddl.semantics();
        const dbVer = this._ddl.getOptionValue('db') as string | null;
        const db23  = dbVer != null && dbVer.length > 0 && 23 <= (getMajorVersion(dbVer) ?? 0);
        switch (sem.base) {
            case 'varchar':   return `varchar2(${sem.varcharLen ?? 4000}${s})`;
            case 'number':    return sem.numericSpec ? `number${sem.numericSpec}` : 'number';
            case 'integer':   return 'integer';
            case 'date':      return 'date';
            case 'timestamp': return 'timestamp';
            case 'tswtz':     return 'timestamp with time zone';
            case 'tswltz':    return 'timestamp with local time zone';
            case 'clob':      return 'clob';
            case 'blob':      return 'blob';
            case 'boolean':   return 'boolean';
            case 'geometry':  return 'sdo_geometry';
            case 'json':      return db23 ? 'json' : `clob check (${sem.colName} is json)`;
            case 'vector':    return `vector${sem.vectorSpec ?? '(*,*,*)'}`;
            default:          return sem.base;
        }
    }

    _buildColumnConstraints(node: IDdlNode, ret: string, sem: SemanticType): string {
        if (node.isOption('unique') || node.isOption('uk')) {
            ret += '\n';
            ret += this._cpad(node) + 'constraint ' + concatNames(this._ddl.objPrefix(), sem.parent_child, this._naming.unq) + ' unique';
        }
        let optQuote = "'";
        if (ret.startsWith('integer') || ret.startsWith('number') || ret.startsWith('date')) optQuote = '';
        if (node.isOption('default')) {
            const value = node.getDefaultValue() ?? '';
            const sqlDateExpressions = ['sysdate', 'current_date', 'current_timestamp', 'systimestamp', 'localtimestamp'];
            if (sem.isNativeBoolean) {
                const boolVal = (value.toUpperCase() === 'Y' || value.toLowerCase() === 'true') ? 'true' : 'false';
                ret += ' default on null ' + boolVal;
            } else if (sqlDateExpressions.includes(value.toLowerCase()))
                ret += ' default on null ' + value;
            else
                ret += ' default on null ' + optQuote + value + optQuote;
        }
        if (node.isOption('nn') || node.indexOf('not') + 1 === node.indexOf('null'))
            if (node.indexOf('pk') < 0) ret += ' not null';
        if (node.isOption('hidden') || node.isOption('invincible')) ret += ' invisible';
        if (!sem.isNativeBoolean) ret += node.genConstraint(optQuote);
        if (sem.needsBoolCheck)
            ret += '\n' + this._cpad(node)
                + 'constraint ' + concatNames(this._ddl.objPrefix(), sem.parent_child)
                + ` check (${node.parseName()} in ('Y','N'))`;
        if (node.isOption('between')) {
            const values = node.getBetweenClause() ?? '';
            ret += ' constraint ' + concatNames(sem.parent_child, this._naming.bet) + '\n';
            ret += '           check (' + node.parseName() + ' between ' + values + ')';
        }
        if (node.isOption('pk')) {
            const typeModifier = ret.startsWith('number')
                ? ' ' + this._pkTypeModifier(this._ddl.objPrefix() + node.parent!.parseName())
                : ' not null';
            ret += typeModifier + '\n';
            ret += this._cpad(node) + 'constraint ' + concatNames(this._ddl.objPrefix(), sem.parent_child, this._naming.pk) + ' primary key';
        }
        if (node.annotations !== null) {
            if (0 <= ret.indexOf('\n'))
                ret += '\n' + this._cpad(node) + 'annotations (' + node.annotations + ')';
            else
                ret += ' annotations (' + node.annotations + ')';
        }
        return ret;
    }

    _genSequence(_node: IDdlNode, objName: string): string {
        if (this._ddl.optionEQvalue('pk', 'SEQ') && this._ddl.optionEQvalue('genpk', true))
            return 'create sequence  ' + objName + '_seq;\n\n';
        return '';
    }

    _genTableHeader(node: IDdlNode, objName: string, immutableKeyword: string, idColName: string | null): string {
        let ret = 'create ' + immutableKeyword + 'table ' + objName + ' (\n';
        const pad = tab + ' '.repeat(node.maxChildNameLen() - 'ID'.length);
        if (idColName !== null && !node.isOption('pk')) {
            ret += tab + idColName + pad + 'number ' + this._pkTypeModifier(objName) + '\n';
            const obj_col = concatNames(this._ddl.objPrefix('no schema') + node.parseName(), '_', idColName);
            ret += tab + tab + ' '.repeat(node.maxChildNameLen()) + 'constraint ' + concatNames(obj_col, this._naming.pk) + ' primary key,\n';
        } else {
            const pkName = node.getExplicitPkName();
            if (pkName !== null && pkName.indexOf(',') < 0) {
                const pkPad = tab + ' '.repeat(node.maxChildNameLen() - pkName.length);
                let type = 'number';
                const child = node.findChild(pkName);
                if (child !== null) type = this.parseType(child);
                ret += tab + pkName + pkPad + type + ',\n';
            }
        }
        return ret;
    }

    _genFkColumns(node: IDdlNode, objName: string): string {
        let ret = '';
        for (let fk in node.fks) {
            let parent = node.fks![fk];
            if (0 < fk.indexOf(',')) {
                const refNode = this._ddl.find(parent);
                const chunks = split_str(fk, ', ');
                for (let i = 0; i < chunks.length; i++) {
                    const col = chunks[i];
                    if (col === ',') continue;
                    const pChild = refNode?.findChild(col);
                    const colPad = tab + ' '.repeat(node.maxChildNameLen() - col.length);
                    ret += tab + col + colPad + (pChild ? this._toOracleType(pChild._inferTypeFull()) : 'number') + ',\n';
                }
                continue;
            }
            let type = 'number';
            const attr = node.findChild(fk);
            if (attr !== null) type = attr.inferType();
            let refNode = this._ddl.find(parent);
            let _id = '';
            if (refNode !== null) {
                type = this._fkOracleType(refNode) ?? type;
            } else {
                refNode = this._ddl.find(fk);
                if (refNode?.isMany2One?.() && !fk.endsWith('_id')) {
                    parent = fk;
                    fk = singular(fk) ?? fk;
                    _id = '_id';
                }
            }
            const fkPad = tab + ' '.repeat(node.maxChildNameLen() - fk.length);
            ret += tab + fk + _id + fkPad + type;
            const refPrefix = this._ddl.find(parent) !== null ? this._ddl.objPrefix() : '';
            if (refNode !== null && (refNode.line < node.line || refNode.isMany2One())) {
                ret += tab + tab + ' '.repeat(node.maxChildNameLen()) + 'constraint ' + objName + '_' + fk + this._naming.fk + '\n';
                let onDelete = '';
                if (node.isOption('cascade')) onDelete = ' on delete cascade';
                else if (node.isOption('setnull')) onDelete = ' on delete set null';
                let notNull = '';
                for (const c in node.children) {
                    const child = node.children[c];
                    if (fk === child.parseName()) {
                        if (child.isOption('nn') || child.isOption('notnull')) notNull = NOT_NULL_LOWER;
                        if (child.isOption('cascade')) onDelete = ' on delete cascade';
                        else if (node.isOption('setnull')) onDelete = ' on delete set null';
                        break;
                    }
                }
                ret += tab + tab + ' '.repeat(node.maxChildNameLen()) + 'references ' + refPrefix + parent + onDelete + notNull + ',\n';
            } else {
                ret += ',\n';
                const alter = 'alter table ' + objName + ' add constraint ' + objName + '_' + fk + '_fk foreign key (' + fk + ') references ' + refPrefix + parent + ';\n';
                if (!this._ddl.postponedAltersSet.has(alter)) {
                    this._ddl.postponedAlters.push(alter);
                    this._ddl.postponedAltersSet.add(alter);
                }
            }
        }
        return ret;
    }

    _genRowKeyColumn(node: IDdlNode, objName: string): string {
        if (!node.hasRowKey()) return '';
        const pad = tab + ' '.repeat(node.maxChildNameLen() - 'ROW_KEY'.length);
        let ret = tab + 'row_key' + pad + `varchar2(30${this._ddl.semantics()})\n`;
        ret += tab + tab + ' '.repeat(node.maxChildNameLen()) + 'constraint ' + objName + '_row_key' + this._naming.unq + ' unique not null,\n';
        return ret;
    }

    _genRegularColumns(node: IDdlNode, _objName: string, idColName: string | null): string {
        let ret = '';
        for (let i = 0; i < node.children.length; i++) {
            const child = node.children[i];
            if (idColName !== null && child.parseName() === 'id') continue;
            if (0 < child.children.length) continue;
            if (child.refId() === null) {
                if (child.parseName() === node.getExplicitPkName()) continue;
                ret += tab + this.generateTable(child) + ',\n';
                for (const type in EXPANDING_TYPES) {
                    if (0 < child.indexOf(type)) {
                        const col = child.parseName().toUpperCase();
                        for (const ext of EXPANDING_TYPES[type]) {
                            const extraCol = col + ext.suffix.toUpperCase();
                            const extPad = tab + ' '.repeat(node.maxChildNameLen() - extraCol.length);
                            ret += tab + extraCol.toLowerCase() + extPad + ext.type(this._ddl) + ',\n';
                        }
                        break;
                    }
                }
            }
        }
        return ret;
    }

    _genRowVersionColumn(node: IDdlNode): string {
        if (!node.hasRowVersion()) return '';
        const pad = tab + ' '.repeat(node.maxChildNameLen() - 'row_version'.length);
        return tab + 'row_version' + pad + 'integer not null,\n';
    }

    _genAuditColumns(node: IDdlNode): string {
        if (!node.hasAuditCols()) return '';
        let auditDateType = String(this._ddl.getOptionValue('auditdate') || this._ddl.getOptionValue('Date Data Type') || '').toLowerCase();
        let ret = '';
        const created = String(this._ddl.getOptionValue('createdcol') ?? '');
        ret += tab + created + tab + ' '.repeat(node.maxChildNameLen() - created.length) + auditDateType + ' not null,\n';
        const createdby = String(this._ddl.getOptionValue('createdbycol') ?? '');
        ret += tab + createdby + tab + ' '.repeat(node.maxChildNameLen() - createdby.length) + `varchar2(255${this._ddl.semantics()}) not null,\n`;
        const updated = String(this._ddl.getOptionValue('updatedcol') ?? '');
        ret += tab + updated + tab + ' '.repeat(node.maxChildNameLen() - updated.length) + auditDateType + ' not null,\n';
        const updatedby = String(this._ddl.getOptionValue('updatedbycol') ?? '');
        ret += tab + updatedby + tab + ' '.repeat(node.maxChildNameLen() - updatedby.length) + `varchar2(255${this._ddl.semantics()}) not null,\n`;
        return ret;
    }

    _genAdditionalColumns(node: IDdlNode): string {
        let ret = '';
        const cols = this._ddl.additionalColumns();
        for (const col in cols) {
            const type = cols[col];
            const pad  = tab + ' '.repeat(node.maxChildNameLen() - col.length);
            ret += tab + col.toUpperCase() + pad + type + ' not null,\n';
        }
        return ret;
    }

    _genTableFooter(node: IDdlNode, objName: string, immutableKeyword: string, _db23plus: boolean): string {
        const tableAnnotations = node.annotations !== null ? '\nannotations (' + node.annotations + ')' : '';
        let compressClause = '';
        if (this._ddl.optionEQvalue('compress', 'yes') || node.isOption('compress'))
            compressClause = _db23plus ? ' row store compress advanced' : ' compress';
        let immutableSuffix = (immutableKeyword !== '') ? '\nno drop until 0 days idle\nno delete until 16 days after insert' : '';
        if (immutableSuffix !== '' && compressClause !== '') compressClause = '\n' + compressClause.trimStart();
        let ret = ')' + immutableSuffix + compressClause + tableAnnotations + ';\n\n';
        if (node.isOption('audit') && !node.isOption('auditcols') &&
            !node.isOption('audit', 'col') && !node.isOption('audit', 'cols') && !node.isOption('audit', 'columns')) {
            ret += 'audit all on ' + objName + ';\n\n';
        }
        if (node.isOption('flashback') || node.isOption('fda')) {
            const archiveName = String(node.getOptionValue('flashback') || node.getOptionValue('fda') || '').trim();
            ret += 'alter table ' + objName + ' flashback archive' + (0 < archiveName.length ? ' ' + archiveName : '') + ';\n\n';
        }
        return ret;
    }

    _genMultiColFkAlters(node: IDdlNode, objName: string): string {
        let ret = '';
        for (const fk in node.fks) {
            if (0 < fk.indexOf(',')) {
                const parent = node.fks![fk];
                ret += 'alter table ' + objName + ' add constraint ' + parent + '_' + objName + '_fk foreign key (' + fk + ') references ' + parent + ';\n\n';
            }
        }
        return ret;
    }

    _genIndexes(node: IDdlNode, objName: string, _db23plus: boolean): string {
        let ret = '';
        let num = 1;
        for (const fk in node.fks) {
            if (!node.isMany2One()) {
                const col = fk ?? (singular(node.fks![fk]) + '_id');
                if (num === 1) ret += '-- table index\n';
                ret += 'create index ' + objName + this._naming.idx + (num++) + ' on ' + objName + ' (' + col + ');\n\n';
            }
        }
        const cut = node.getOptionValue('pk');
        if (cut) ret += 'alter table ' + objName + ' add constraint ' + objName + this._naming.pk + ' primary key (' + cut + ');\n\n';

        let cutUnq = node.getOptionValue('unique') ?? node.getOptionValue('uk');
        if (cutUnq !== null)
            ret += 'alter table ' + objName + ' add constraint ' + objName + this._naming.uk + ' unique (' + cutUnq + ');\n\n';

        for (let i = 0; i < node.children.length; i++) {
            const child = node.children[i];
            if (child.isOption('idx') || child.isOption('index')) {
                if (num === 1) ret += '-- table index\n';
                ret += 'create index ' + objName + this._naming.idx + (num++) + ' on ' + objName + ' (' + child.parseName() + ');\n';
            }
        }
        if (_db23plus) {
            for (let i = 0; i < node.children.length; i++) {
                const child = node.children[i];
                if (child.children.length === 0 && child.inferType() === 'vector') {
                    ret += 'create vector index ' + objName + '_vi' + (num++) + ' on ' + objName + ' (' + child.parseName() + ')\n';
                    ret += '    organization neighbor partitions\n';
                    ret += '    with distance cosine;\n\n';
                }
            }
        }
        for (let i = 0; i < node.children.length; i++) {
            const child = node.children[i];
            if (child.children.length === 0 && child.inferType() === 'geometry') {
                ret += 'create index ' + objName + '_si' + (num++) + ' on ' + objName + ' (' + child.parseName() + ')\n';
                ret += '    indextype is mdsys.spatial_index_v2;\n\n';
            }
        }
        return ret;
    }

    _genComments(node: IDdlNode, objName: string): string {
        let ret = '';
        const tableComment = node.getAnnotationValue('DESCRIPTION') || node.comment;
        if (tableComment !== null) ret += "comment on table " + objName + " is '" + tableComment + "';\n";
        for (let i = 0; i < node.children.length; i++) {
            const child = node.children[i];
            const colComment = child.getAnnotationValue('DESCRIPTION') || child.comment;
            if (colComment !== null && child.children.length === 0)
                ret += "comment on column " + objName + '.' + child.parseName() + " is '" + colComment + "';\n";
        }
        return ret;
    }

    _orderedTableNodes(node: DdlNode): DdlNode[] {
        const ret: DdlNode[] = [node];
        const descendants = node.descendants();
        for (let i = 1; i < descendants.length; i++) {
            const desc = descendants[i];
            if (desc.children.length === 0) continue;
            if (desc.isMany2One()) {
                if (!this._isContainedIn(desc, ret)) ret.unshift(desc);
            } else if (!this._isContainedIn(desc, ret))
                ret.push(desc);
        }
        return ret;
    }

    _isContainedIn(node: DdlNode, nodes: DdlNode[]): boolean {
        for (const i in nodes)
            if (nodes[i].parseName() === node.parseName()) return true;
        return false;
    }

    parseType(node: IDdlNode): string {
        if (node.children !== null && 0 < node.children.length) return 'table';
        const t = node.inferType();
        if (t === 'view' || t === 'dv') return t;
        if (node.parent === null) return 'table';
        const sem = node._inferTypeFull();
        return this._buildColumnConstraints(node, this._toOracleType(sem), sem);
    }

    generateTable(node: IDdlNode): string {
        if (node.children.length === 0 && 0 < node.apparentDepth()) {
            let pad = tab;
            if (node.parent !== undefined && node.parent !== null)
                pad += ' '.repeat(node.parent.maxChildNameLen() - node.parseName().length);
            return node.parseName() + pad + this.parseType(node);
        }

        node.lateInitFks();
        const objName = this._ddl.objPrefix() + node.parseName();

        if (node.isOption('soda')) {
            let ret = 'create table ' + objName + ' (\n';
            ret += tab + 'id              varchar2(255' + this._ddl.semantics() + ') not null\n';
            ret += tab + '                constraint ' + objName + '_id_pk primary key,\n';
            ret += tab + 'created_on      timestamp default sys_extract_utc(systimestamp) not null,\n';
            ret += tab + 'last_modified   timestamp default sys_extract_utc(systimestamp) not null,\n';
            ret += tab + 'version         varchar2(255' + this._ddl.semantics() + ') not null,\n';
            ret += tab + 'json_document   json\n';
            ret += ');\n\n';
            return ret;
        }

        const _dbVer    = this._ddl.getOptionValue('db') as string | null;
        const _db23plus = _dbVer !== null && _dbVer.length > 0 && 23 <= (getMajorVersion(_dbVer) ?? 0);
        let immutableKeyword = '';
        if (node.isOption('immutable') && _db23plus) immutableKeyword = 'immutable ';
        const idColName = node.getGenIdColName();

        let ret = this._genSequence(node, objName);
        ret += this._genTableHeader(node, objName, immutableKeyword, idColName);
        ret += this._genFkColumns(node, objName);
        ret += this._genRowKeyColumn(node, objName);
        ret += this._genRegularColumns(node, objName, idColName);
        ret += this._genRowVersionColumn(node);
        ret += this._genAuditColumns(node);
        ret += this._genAdditionalColumns(node);
        ret += node.genConstraint();
        ret = trimTrailingComma(ret);
        ret += this._genTableFooter(node, objName, immutableKeyword, _db23plus);
        ret += this._genMultiColFkAlters(node, objName);
        ret += this._genIndexes(node, objName, _db23plus);
        ret += this._genComments(node, objName);
        ret += '\n';
        return ret;
    }

    generateDDL(node: IDdlNode): string {
        if (node.inferType() === 'view' || node.inferType() === 'dv') return '';
        const tables = this._orderedTableNodes(node as DdlNode);
        let ret = '';
        for (let i = 0; i < tables.length; i++) ret += this.generateTable(tables[i]);
        return ret;
    }

    generateDrop(node: IDdlNode): string {
        const objName = this._ddl.objPrefix() + node.parseName();
        const dbVer   = this._ddl.getOptionValue('db') as string | null;
        const ifExists = dbVer && dbVer.length > 0 && 23 <= (getMajorVersion(dbVer) ?? 0) ? 'if exists ' : '';
        let ret = '';
        if (node.inferType() === 'view') ret = 'drop view ' + ifExists + objName + ';\n';
        if (node.inferType() === 'table') {
            ret = 'drop table ' + ifExists + objName + ' cascade constraints;\n';
            if (this._ddl.optionEQvalue('api', 'yes')) ret += 'drop package ' + ifExists + objName + '_api;\n';
            if (this._ddl.optionEQvalue('pk', 'SEQ'))  ret += 'drop sequence ' + ifExists + objName + this._naming.seq + ';\n';
        }
        return ret.toLowerCase();
    }

    generateView(node: DdlNode): string {
        if (node.inferType() !== 'view' && node.inferType() !== 'dv') return '';
        if (this._ddl.optionEQvalue('Duality View', 'yes') || node.inferType() === 'dv') {
            try {
                return this.generateDualityView(node);
            } catch (e) {
                if ((e as Error).message === node.one2many2oneUnsupoorted) return '';
                throw e;
            }
        }
        const objName = this._ddl.objPrefix() + node.parseName();
        const chunks  = node.src;
        const setup   = this._buildViewSetup(node, chunks);
        if (setup === null) return '';
        let ret = 'create or replace view ' + objName;
        if (node.annotations !== null) ret += '\nannotations (' + node.annotations + ')';
        ret += ' as\n';
        ret += 'select\n';
        ret += this._buildViewColList(node, chunks, setup.aliasMap, setup.tblCache, setup.colCnts, setup.tblTransCols, setup.maxLen);
        ret = trimTrailingComma(ret);
        const { sortedTables, joinConditions } = this._sortViewTables(node, chunks, setup.tblCache);
        ret += 'from\n';
        ret += this._buildViewFromClause(node, sortedTables, setup.aliasMap, joinConditions, setup.tblTransCols, setup.tblCache);
        ret = ret.toLowerCase();
        if (ret.endsWith('\n')) ret = ret.trimEnd();
        if (!ret.endsWith('\n')) ret += '\n';
        ret += '/\n';
        return ret.toLowerCase();
    }

    _buildViewSetup(_node: DdlNode, chunks: LexerToken[]): {
        aliasMap: Record<string, string>;
        tblCache: Record<string, DdlNode | null>;
        maxLen: number;
        colCnts: Record<string, number>;
        tblTransCols: Record<string, Record<string, boolean>>;
    } | null {
        const aliasMap: Record<string, string> = {};
        const tblCache: Record<string, DdlNode | null> = {};
        for (let i = 2; i < chunks.length; i++) {
            aliasMap[chunks[i].value] = amend_reserved_word(chunks[i].value);
            tblCache[chunks[i].value] = this._ddl.find(chunks[i].value) as DdlNode | null;
        }
        let maxLen = 0;
        for (let i = 2; i < chunks.length; i++) {
            const tbl = tblCache[chunks[i].value];
            if (tbl === null) return null;
            const alias = aliasMap[chunks[i].value];
            let len = (alias + '.id').length;
            if (maxLen < len) maxLen = len;
            for (let j = 0; j < tbl.children.length; j++) {
                const child = tbl.children[j];
                len = (alias + '.' + child.parseName()).length;
                if (maxLen < len) maxLen = len;
            }
        }
        const colCnts: Record<string, number> = {};
        for (let i = 2; i < chunks.length; i++) {
            const tbl = tblCache[chunks[i].value];
            if (tbl === null) continue;
            for (let j = 0; j < tbl.children.length; j++) {
                const col = tbl.children[j].parseName();
                colCnts[col] = (colCnts[col] ?? 0) + 1;
            }
        }
        for (let i = 2; i < chunks.length; i++) {
            const idAlias = (singular(chunks[i].value) ?? chunks[i].value) + '_id';
            colCnts[idAlias] = (colCnts[idAlias] ?? 0) + 1;
        }
        const tblTransCols: Record<string, Record<string, boolean>> = {};
        for (let i = 2; i < chunks.length; i++) {
            const tbl = tblCache[chunks[i].value];
            if (tbl !== null) {
                const tc = tbl.getTransColumns();
                if (tc.length > 0) {
                    const transNames: Record<string, boolean> = {};
                    for (let t = 0; t < tc.length; t++) transNames[tc[t].parseName()] = true;
                    tblTransCols[chunks[i].value] = transNames;
                }
            }
        }
        return { aliasMap, tblCache, maxLen, colCnts, tblTransCols };
    }

    _buildViewColList(
        _node: DdlNode, chunks: LexerToken[],
        aliasMap: Record<string, string>,
        tblCache: Record<string, DdlNode | null>,
        colCnts: Record<string, number>,
        tblTransCols: Record<string, Record<string, boolean>>,
        maxLen: number,
    ): string {
        let ret = '';
        for (let i = 2; i < chunks.length; i++) {
            const tbl = tblCache[chunks[i].value];
            if (tbl === null) continue;
            const tblName    = chunks[i].value;
            const alias      = aliasMap[tblName];
            const transNames = tblTransCols[tblName] ?? {};
            const pad = ' '.repeat(maxLen - (alias.length + 1 + 2));
            ret += tab + alias + '.id' + tab + pad + (singular(tblName) ?? tblName) + '_id,\n';
            for (let j = 0; j < tbl.children.length; j++) {
                const child = tbl.children[j];
                if (child.children.length === 0) {
                    const cname         = child.parseName();
                    let disambiguator   = '';
                    if (1 < (colCnts[cname] ?? 0)) disambiguator = (singular(tblName) ?? tblName) + '_';
                    if (transNames[cname]) {
                        const tAlias = 't_' + tblName;
                        const expr   = `coalesce(${tAlias}.trans_${cname}, ${alias}.${cname})`;
                        ret += tab + expr + tab + disambiguator + cname + ',\n';
                    } else {
                        const colPad = ' '.repeat(maxLen - (alias.length + 1 + cname.length));
                        ret += tab + alias + '.' + cname + tab + colPad + disambiguator + cname + ',\n';
                    }
                }
            }
            if (tbl.hasRowVersion()) {
                const rvPad = tab + ' '.repeat(tbl.maxChildNameLen() - 'row_version'.length);
                ret += tab + alias + '.row_version' + rvPad + (singular(tblName) ?? tblName) + '_row_version,\n';
            }
            if (tbl.hasRowKey()) {
                const rkPad = tab + ' '.repeat(tbl.maxChildNameLen() - 'ROW_KEY'.length);
                ret += tab + alias + '.ROW_KEY' + rkPad + (singular(tblName) ?? tblName) + '_ROW_KEY,\n';
            }
            if (tbl.hasAuditCols()) {
                for (const colKey of ['createdcol', 'createdbycol', 'updatedcol', 'updatedbycol']) {
                    const colName = String(this._ddl.getOptionValue(colKey) ?? '');
                    const acPad   = tab + ' '.repeat(tbl.maxChildNameLen() - colName.length);
                    ret += tab + alias + '.' + colName + acPad + (singular(tblName) ?? tblName) + '_' + colName + ',\n';
                }
            }
        }
        return ret;
    }

    _sortViewTables(_node: DdlNode, chunks: LexerToken[], tblCache: Record<string, DdlNode | null>): {
        sortedTables: string[];
        joinConditions: Record<string, Array<{ fkCol: string; parentTable: string }>>;
    } {
        const viewTableNames: Record<string, boolean> = {};
        for (let i = 2; i < chunks.length; i++) viewTableNames[chunks[i].value] = true;

        const joinConditions: Record<string, Array<{ fkCol: string; parentTable: string }>> = {};
        for (let i = 2; i < chunks.length; i++) {
            const nameA = chunks[i].value;
            const nodeA = tblCache[nameA];
            if (nodeA === null) continue;
            for (const k in nodeA.fks) {
                const parent = nodeA.fks![k];
                if (viewTableNames[parent] && parent !== nameA) {
                    if (!joinConditions[nameA]) joinConditions[nameA] = [];
                    joinConditions[nameA].push({ fkCol: k, parentTable: parent });
                }
            }
        }

        const emitted: Record<string, boolean> = {};
        const sortedTables: string[] = [];
        for (let i = 2; i < chunks.length; i++) {
            const name = chunks[i].value;
            if (!joinConditions[name]) { sortedTables.push(name); emitted[name] = true; }
        }
        let remaining: string[] = [];
        for (let i = 2; i < chunks.length; i++) {
            if (joinConditions[chunks[i].value]) remaining.push(chunks[i].value);
        }
        while (remaining.length > 0) {
            let progress = false;
            const next: string[] = [];
            for (let r = 0; r < remaining.length; r++) {
                const name  = remaining[r];
                const conds = joinConditions[name];
                const allParentsEmitted = conds.every(c => emitted[c.parentTable]);
                if (allParentsEmitted) {
                    sortedTables.push(name); emitted[name] = true; progress = true;
                } else {
                    next.push(name);
                }
            }
            remaining = next;
            if (!progress) {
                for (let r = 0; r < remaining.length; r++) { sortedTables.push(remaining[r]); emitted[remaining[r]] = true; }
                break;
            }
        }
        return { sortedTables, joinConditions };
    }

    _buildViewFromClause(
        _node: DdlNode,
        sortedTables: string[],
        aliasMap: Record<string, string>,
        joinConditions: Record<string, Array<{ fkCol: string; parentTable: string }>>,
        tblTransCols: Record<string, Record<string, boolean>>,
        tblCache: Record<string, DdlNode | null>,
    ): string {
        let ret = '';
        const transContext = this._ddl.getOptionValue('transcontext');
        for (let si = 0; si < sortedTables.length; si++) {
            const tblName = sortedTables[si];
            const alias   = aliasMap[tblName];
            let tblExpr   = alias;
            if (this._ddl.objPrefix()) tblExpr = this._ddl.objPrefix() + tblName + ' ' + alias;
            if (si === 0) {
                ret += tab + tblExpr + '\n';
            } else if (joinConditions[tblName]) {
                const conds = joinConditions[tblName];
                ret += tab + 'left join ' + tblExpr + '\n';
                for (let c = 0; c < conds.length; c++) {
                    const aliasB  = aliasMap[conds[c].parentTable];
                    const prefix  = (c === 0) ? 'on ' : 'and ';
                    ret += tab + tab + prefix + alias + '.' + conds[c].fkCol + ' = ' + aliasB + '.id\n';
                }
            } else {
                ret += tab + 'cross join ' + tblExpr + '\n';
            }
            if (tblTransCols[tblName]) {
                const tblNode    = tblCache[tblName]!;
                const transName  = this._ddl.objPrefix() + tblName + '_trans';
                const tAlias     = 't_' + tblName;
                const fkCol      = (singular(tblName) ?? tblName) + '_id';
                const pkCol      = tblNode.getGenIdColName() ?? tblNode.getExplicitPkName() ?? 'id';
                ret += tab + 'left join ' + transName + ' ' + tAlias + '\n';
                ret += tab + tab + 'on ' + tAlias + '.' + fkCol + ' = ' + alias + '.' + pkCol + '\n';
                ret += tab + tab + 'and ' + tAlias + '.language_code = ' + transContext + '\n';
            }
        }
        return ret;
    }

    restEnable(node: IDdlNode): string {
        if (node.inferType() !== 'table') return '';
        if (!node.isOption('rest')) return '';
        const name    = node.parseName();
        const isQuoted = name.indexOf('"') === 0;
        let objName = this._ddl.objPrefix() + name;
        if (isQuoted) objName = this._ddl.objPrefix() + name.substring(1, name.length - 1);
        else objName = (this._ddl.objPrefix() + name).toUpperCase();
        return "begin\n" + tab + "ords.enable_object(p_enabled=>TRUE, p_object=>'" + objName + "');\nend;\n/\n";
    }

    generateTrigger(node: IDdlNode): string {
        if (node.inferType() !== 'table') return '';
        if (node.isOption('soda')) return '';
        return this._generateBITrigger(node) + this._generateBUTrigger(node);
    }

    _generateBITrigger(node: IDdlNode): string {
        const editionable = this._ddl.optionEQvalue('editionable', 'yes') ? ' editionable' : '';
        const objName     = (this._ddl.objPrefix() + node.parseName()).toLowerCase();
        let ret = `create or replace${editionable} trigger ${objName}${this._naming.bi}\n`;
        ret += '    before insert\n';
        ret += '    on ' + objName + '\n';
        ret += '    for each row\n';

        if (node.hasRowKey()) {
            ret += `declare
    function compress_int (n in integer ) return varchar2
    as
        ret       varchar2(30);
        quotient  integer;
        remainder integer;
        digit     char(1);
    begin
        ret := null; quotient := n;
        <<compress_loop>>
        while quotient > 0
        loop
            remainder := mod(quotient, 10 + 26);
            quotient := floor(quotient  / (10 + 26));
            if remainder < 26 then
                digit := chr(ascii('A') + remainder);
            else
                digit := chr(ascii('0') + remainder - 26);
            end if;
            ret := digit || ret;
        end loop compress_loop;
        if length(ret) < 5 then ret := lpad(ret, 4, 'A'); end if ;
        return upper(ret);
    end compress_int;
`;
        }

        ret += 'begin\n';
        let OK  = false;
        const user = node.apexUser();
        if (node.hasRowKey()) { ret += '    :new.row_key := compress_int(row_key_seq.nextval);\n'; OK = true; }
        for (let i = 0; i < node.children.length; i++) {
            const child = node.children[i];
            const method = this._caseMethod(child);
            if (method === '') continue;
            ret += '    :new.' + child.parseName().toLowerCase() + ' := ' + method + '(:new.' + child.parseName().toLowerCase() + ');\n';
            OK = true;
        }
        if (node.hasRowVersion()) { ret += '    :new.row_version := 1;\n'; OK = true; }
        if (node.hasAuditCols()) {
            const sysDateFn = node.auditSysDateFn();
            ret += '    :new.' + this._ddl.getOptionValue('createdcol')  + ' := ' + sysDateFn + ';\n';
            ret += '    :new.' + this._ddl.getOptionValue('createdbycol') + ' := ' + user + ';\n';
            ret += '    :new.' + this._ddl.getOptionValue('updatedcol')  + ' := ' + sysDateFn + ';\n';
            ret += '    :new.' + this._ddl.getOptionValue('updatedbycol') + ' := ' + user + ';\n';
            OK = true;
        }
        const cols = this._ddl.additionalColumns();
        for (const col in cols) {
            const type = cols[col];
            ret += '    if :new.' + col + ' is null then\n';
            if (type.startsWith('INT')) ret += '        ' + col + ' := 0;\n';
            else ret += "        " + col + " := 'N/A';\n";
            ret += '    end if;\n';
            OK = true;
        }
        if (!OK) return '';
        ret += 'end ' + objName + this._naming.bi + ';\n/\n\n';
        return ret;
    }

    _generateBUTrigger(node: IDdlNode): string {
        if (node.isOption('immutable')) return '';
        let hasLowerUpper = false;
        for (let i = 0; i < node.children.length; i++) {
            if (node.children[i].isOption('lower') || node.children[i].isOption('upper')) {
                hasLowerUpper = true; break;
            }
        }
        const hasRowVersion = node.hasRowVersion();
        const hasAuditCols  = node.hasAuditCols();
        if (!hasLowerUpper && !hasRowVersion && !hasAuditCols) return '';
        const editionable = this._ddl.optionEQvalue('editionable', 'yes') ? ' editionable' : '';
        const objName     = (this._ddl.objPrefix() + node.parseName()).toLowerCase();
        let ret = `create or replace${editionable} trigger ${objName}${this._naming.bu}\n`;
        ret += '    before update\n    on ' + objName + '\n    for each row\nbegin\n';
        const user = node.apexUser();
        for (let i = 0; i < node.children.length; i++) {
            const child  = node.children[i];
            const method = this._caseMethod(child);
            if (method === '') continue;
            ret += '    :new.' + child.parseName().toLowerCase() + ' := ' + method + '(:new.' + child.parseName().toLowerCase() + ');\n';
        }
        if (hasRowVersion) ret += '    :new.row_version := nvl(:old.row_version, 0) + 1;\n';
        if (hasAuditCols) {
            const sysDateFn = node.auditSysDateFn();
            ret += '    :new.' + this._ddl.getOptionValue('updatedcol')  + ' := ' + sysDateFn + ';\n';
            ret += '    :new.' + this._ddl.getOptionValue('updatedbycol') + ' := ' + user + ';\n';
        }
        ret += 'end ' + objName + this._naming.bu + ';\n/\n\n';
        return ret;
    }

    generateImmutableTrigger(node: IDdlNode): string {
        if (node.inferType() !== 'table') return '';
        if (!node.isOption('immutable')) return '';
        const dbVer = this._ddl.getOptionValue('db') as string | null;
        if (dbVer && dbVer.length > 0 && 23 <= (getMajorVersion(dbVer) ?? 0)) return '';
        const objName = this._ddl.objPrefix() + node.parseName();
        let ret = 'create or replace trigger ' + this._naming.immutable_prefix + objName.toLowerCase() + this._naming.immutable_suffix + '\n';
        ret += '    before update or delete\n    on ' + objName.toLowerCase() + '\ndeclare\n';
        ret += "    co_immutable_err  constant pls_integer      := -20055;\n";
        ret += "    co_immutable_msg  constant varchar2(200 char) := '" + objName.toLowerCase() + " is immutable';\n";
        ret += 'begin\n    raise_application_error(co_immutable_err, co_immutable_msg);\nend;\n/\n\n';
        return ret;
    }

    procDecl(node: IDdlNode, kind: string): string {
        const modifier = kind !== 'get' ? ' default null' : '';
        const mode     = kind !== 'get' ? ' in' : 'out';
        let ret = tab + 'procedure ' + kind + '_row (\n';
        const idColName = node.getPkName();
        const pkChild = node.getGenIdColName() !== null ? null : node.findChild(node.getExplicitPkName()!);
        const pkPlsqlType = pkChild ? pkChild.getPlsqlType() : node.getPkType();
        ret += tab + tab + 'p_' + idColName + '        in  ' + pkPlsqlType + modifier;
        for (const fk in node.fks) {
            const parent  = node.fks![fk];
            let type = 'integer';
            const refNode = this._ddl.find(parent);
            if (refNode !== null) type = this._fkPlsqlType(refNode) ?? type;
            ret += ',\n' + tab + tab + 'P_' + fk + '   ' + mode + '  ' + type + modifier;
        }
        for (const child of node.regularColumns())
            ret += ',\n' + tab + tab + 'P_' + child.parseName() + '   ' + mode + '  ' + child.getPlsqlType() + modifier;
        ret += '\n    )';
        return ret;
    }

    _getRowBody(node: IDdlNode): string {
        const idColName = node.getPkName();
        const objName   = this._ddl.objPrefix() + node.parseName();
        let ret = tab + 'is \n' + tab + 'begin \n';
        const selectCols: string[] = [];
        const intoCols:   string[] = [];
        for (const fk in node.fks) { selectCols.push(fk); intoCols.push('p_' + fk); }
        for (const gchild of node.regularColumns()) {
            const cn = gchild.parseName().toLowerCase();
            selectCols.push(cn); intoCols.push('p_' + cn);
        }
        if (selectCols.length > 0) {
            const pad = tab + tab + '       ';
            ret += tab + tab + 'select ' + selectCols.join(',\n' + pad) + '\n';
            ret += tab + tab + '  into ' + intoCols.join(',\n' + pad) + '\n';
            ret += tab + tab + '  from ' + objName + '\n';
            ret += tab + tab + ' where ' + idColName + ' = p_' + idColName + ';\n';
        }
        ret += tab + 'exception\n' + tab + tab + 'when no_data_found then\n' + tab + tab + tab + 'null;\n';
        ret += tab + 'end get_row;\n \n';
        return ret;
    }

    _insertRowBody(node: IDdlNode): string {
        const idColName = node.getPkName();
        const objName   = this._ddl.objPrefix() + node.parseName();
        let ret = tab + 'is \n' + tab + 'begin \n';
        ret += tab + tab + 'insert into ' + objName + ' ( \n' + tab + tab + tab + idColName;
        for (const fk in node.fks) ret += ',\n' + tab + tab + tab + fk;
        for (const child of node.regularColumns()) ret += ',\n' + tab + tab + tab + child.parseName().toLowerCase();
        ret += '\n' + tab + tab + ') values ( \n' + tab + tab + tab + 'p_' + idColName;
        for (const fk in node.fks) ret += ',\n' + tab + tab + tab + 'p_' + fk;
        for (const child of node.regularColumns()) ret += ',\n' + tab + tab + tab + 'p_' + child.parseName();
        ret += '\n' + tab + tab + ');';
        ret += '\n' + tab + 'end insert_row;\n \n \n';
        return ret;
    }

    _updateRowBody(node: IDdlNode): string {
        const idColName = node.getPkName();
        const objName   = this._ddl.objPrefix() + node.parseName();
        let ret = tab + 'is \n' + tab + 'begin \n';
        ret += tab + tab + 'update  ' + objName + ' set \n' + tab + tab + tab + idColName + ' = p_' + idColName;
        for (const fk in node.fks) ret += ',\n' + tab + tab + tab + fk + ' = P_' + fk;
        for (const child of node.regularColumns())
            ret += ',\n' + tab + tab + tab + child.parseName().toLowerCase() + ' = P_' + child.parseName().toLowerCase();
        ret += '\n' + tab + tab + 'where ' + idColName + ' = p_' + idColName + ';';
        ret += '\n' + tab + 'end update_row;\n \n \n';
        return ret;
    }

    generateTAPI(node: IDdlNode): string {
        if (node.children.length === 0) return '';
        const objName   = this._ddl.objPrefix() + node.parseName();
        let ret = ('create or replace package ' + objName.toLowerCase() + '_API\nis\n\n').toLowerCase();
        ret += this.procDecl(node, 'get') + ';\n\n';
        ret += this.procDecl(node, 'insert') + ';\n\n';
        ret += this.procDecl(node, 'update') + ';\n\n';
        const idColName = node.getPkName();
        ret += '    procedure delete_row (\n        p_' + idColName + '              in integer\n    );\n'
             + 'end ' + objName.toLowerCase() + '_api;\n/\n\n';
        ret += ('create or replace package body ' + objName.toLowerCase() + '_API\nis\n\n').toLowerCase();
        ret += this.procDecl(node, 'get') + '\n' + this._getRowBody(node);
        ret += this.procDecl(node, 'insert') + '\n' + this._insertRowBody(node);
        ret += this.procDecl(node, 'update') + '\n' + this._updateRowBody(node);
        ret += '    procedure delete_row (\n        p_' + idColName + '              in integer\n    )\n'
             + '    is\n    begin\n        delete from ' + objName.toLowerCase() + ' where ' + idColName + ' = p_' + idColName + ';\n'
             + '    end delete_row;\n'
             + 'end ' + objName.toLowerCase() + '_api;\n/\n';
        return ret.toLowerCase();
    }

    generateData(node: IDdlNode, dataObj: unknown): string {
        resetSeed();
        if (this._ddl.optionEQvalue('inserts', false)) return '';
        const tab2inserts = this.inserts4tbl(node as DdlNode, dataObj);
        const tables      = this._orderedTableNodes(node as DdlNode);
        let ret = '';
        for (let i = 0; i < tables.length; i++) {
            const objName = this._ddl.objPrefix() + tables[i].parseName();
            const inserts = (tab2inserts as Record<string, string>)[objName];
            if (inserts !== null && inserts !== undefined) ret += inserts;
        }
        return ret;
    }

    inserts4tbl(node: DdlNode, dataObj: unknown): Record<string, string> {
        let tab2inserts: Record<string, string> = {};
        if (this._ddl.optionEQvalue('inserts', false)) return {};
        const objName = this._ddl.objPrefix() + node.parseName();
        let insert = '';
        for (let i = 0; i < node.cardinality(); i++) {
            let elem: unknown = null;
            if (dataObj !== null && dataObj !== undefined) {
                const tbl = (dataObj as Record<string, unknown>)[objName];
                if (tbl !== null && tbl !== undefined && Array.isArray(tbl)) elem = tbl[i];
            }
            insert += this._buildInsertStatement(node, i, elem, objName);
        }
        if (insert !== '') insert += '\ncommit;\n\n';
        const idColName = node.getGenIdColName();
        if (idColName !== null && 1 < node.cardinality() && !this._ddl.optionEQvalue('pk', 'guid')) {
            insert += 'alter table ' + objName + '\nmodify ' + idColName + ' generated always  as identity restart start with ' + (node.cardinality() + 1) + ';\n\n';
        }
        tab2inserts[objName] = insert;
        for (let i = 0; i < node.children.length; i++) {
            const child = node.children[i];
            if (0 < child.children.length)
                tab2inserts = { ...tab2inserts, ...this.inserts4tbl(child, dataObj) };
        }
        return tab2inserts;
    }

    _buildInsertStatement(node: DdlNode, i: number, elem: unknown, objName: string): string {
        let insert = 'insert into ' + objName + ' (\n';
        const idColName = node.getGenIdColName();
        let pkName:  string | null = null;
        let pkValue: unknown = null;
        if (idColName !== null) {
            pkName = idColName;
            insert += tab + pkName + ',\n';
        } else {
            pkName = node.getExplicitPkName();
            if (pkName !== null) insert += tab + pkName + ',\n';
        }
        for (let fk in node.fks) {
            let parent  = node.fks![fk];
            let _id = '';
            let refNode = this._ddl.find(parent);
            if (refNode === null) {
                refNode = this._ddl.find(fk);
                if (refNode?.isMany2One?.() && !fk.endsWith('_id')) {
                    parent = fk; fk = singular(fk) ?? fk; _id = '_id';
                }
            }
            insert += tab + fk + _id + ',\n';
        }
        for (const child of node.regularColumns()) {
            if (idColName !== null && child.parseName() === 'id') continue;
            if (child.isOption('pk')) continue;
            insert += tab + child.parseName() + ',\n';
        }
        insert = trimTrailingComma(insert);
        insert += ') values (\n';
        if (idColName !== null) {
            pkValue = i + 1;
            insert += tab + pkValue + ',\n';
        } else if (pkName !== null) {
            const field = pkName;
            const tmp = getValue(this._ddl.data, null, field, node.parseName());
            let v: unknown = -1;
            if (elem !== null && elem !== undefined) v = (elem as Record<string, unknown>)[field];
            if (tmp !== null && tmp !== undefined && (tmp as unknown[])[i] !== null && (tmp as unknown[])[i] !== undefined)
                v = (tmp as unknown[])[i];
            if (v !== -1 && typeof v === 'string') v = "'" + v + "'";
            pkValue = v !== -1 ? v : i + 1;
            insert += tab + pkValue + ',\n';
        }
        for (const fk in node.fks) {
            const ref = node.fks![fk];
            const { type, values } = this._resolveFkSampleValues(node, fk, ref, elem, pkValue, objName);
            insert += tab + String(translate(String(this._ddl.getOptionValue('Data Language') ?? 'EN'), generateSample(objName, (singular(ref) ?? ref) + '_id', type, values))) + ',\n';
        }
        for (const child of node.regularColumns()) {
            if (idColName !== null && child.parseName() === 'id') continue;
            if (child.parseName() === node.getExplicitPkName()) continue;
            let values = child.parseValues();
            const cname = child.parseName();
            if (elem !== null && elem !== undefined) {
                const v = (elem as Record<string, unknown>)[cname];
                if (v !== null && v !== undefined) values = [v as string];
            }
            const datum = generateSample(objName, cname, this._toOracleType(child._inferTypeFull()), values);
            insert += tab + String(translate(String(this._ddl.getOptionValue('Data Language') ?? 'EN'), datum)) + ',\n';
        }
        insert = trimTrailingComma(insert);
        insert += ');\n';
        return insert;
    }

    _resolveFkSampleValues(_node: DdlNode, fk: string, ref: string, elem: unknown, pkValue: unknown, objName: string): { type: string; values: unknown[] } {
        const refNode = this._ddl.find(ref);
        let values: unknown[] = [];
        let type = 'INTEGER';
        for (let k = 1; k <= (refNode?.cardinality() ?? 0); k++) values.push(k);
        if (elem !== null && elem !== undefined) {
            const elemObj  = elem as Record<string, unknown>;
            const refData0 = elemObj[fk];
            if (refData0 !== null && refData0 !== undefined) {
                if (typeof refData0 === 'string') type = 'STRING';
                values = [refData0];
            } else {
                const m2mTbl  = objName + '_' + ref;
                const m2mData = (this._ddl.data as Record<string, unknown> | null)?.[m2mTbl];
                if (m2mData !== null && m2mData !== undefined) {
                    for (const idx in m2mData as object) {
                        const row = (m2mData as Record<string, unknown>)[idx] as Record<string, unknown>;
                        if (row[objName + '_id'] === pkValue) {
                            const rd = row[fk];
                            if (rd !== null && rd !== undefined) {
                                if (typeof rd === 'string') type = 'STRING';
                                values = [rd];
                            }
                            break;
                        }
                    }
                } else {
                    const fk1   = refNode?.getPkName() ?? null;
                    const rd    = fk1 !== null ? elemObj[fk1] : undefined;
                    if (rd !== null && rd !== undefined) {
                        if (typeof rd === 'string') type = 'STRING';
                        values = [rd];
                    }
                }
            }
        }
        return { type, values };
    }

    generateDualityView(node: DdlNode): string {
        const chunks = node.src;
        if (chunks.length < 3)
            return '/* duality view requires at least a view name and one table */\n';

        const viewName      = this._ddl.objPrefix() + chunks[0].value;
        const rootTableName = chunks[2].value;
        const rootNode      = this._ddl.find(rootTableName);
        if (rootNode === null)
            return '/* duality view: table ' + rootTableName + ' not found */\n';

        rootNode.lateInitFks();
        const annotations = '@insert @update @delete';
        let ret = 'create or replace json relational duality view ' + viewName + ' as\n';
        ret += this._ddl.objPrefix() + rootNode.parseName() + ' ' + annotations + '\n';
        ret += '{\n';

        const rootPkCol = rootNode.getGenIdColName() ?? rootNode.getExplicitPkName() ?? 'id';
        let rootMaxLen  = '_id'.length;
        for (let i = 0; i < rootNode.children.length; i++) {
            const child = rootNode.children[i];
            if (child.children.length > 0 || child.refId() !== null) continue;
            const len = child.parseName().length;
            if (len > rootMaxLen) rootMaxLen = len;
        }
        for (let t = 3; t < chunks.length; t++) {
            const len = chunks[t].value.length;
            if (len > rootMaxLen) rootMaxLen = len;
        }

        ret += tab + '_id' + ' '.repeat(rootMaxLen - '_id'.length) + ' : ' + rootPkCol + ',\n';

        const fkCols: Record<string, boolean> = {};
        if (rootNode.fks !== null) for (const fk in rootNode.fks) fkCols[fk] = true;
        for (const child of rootNode.regularColumns()) {
            const cname = child.parseName();
            if (cname === rootPkCol || fkCols[cname]) continue;
            ret += tab + cname + ' '.repeat(rootMaxLen - cname.length) + ' : ' + cname + ',\n';
        }

        for (let t = 3; t < chunks.length; t++) {
            const nestedName = chunks[t].value;
            const nestedNode = this._ddl.find(nestedName);
            if (nestedNode === null) continue;
            nestedNode.lateInitFks();

            let isChild = false;
            if (nestedNode.fks !== null) {
                for (const fk in nestedNode.fks) {
                    if (nestedNode.fks[fk] === rootNode.parseName()) { isChild = true; break; }
                }
            }

            const nestedPkCol = nestedNode.getGenIdColName() ?? nestedNode.getExplicitPkName() ?? 'id';
            let nestedMaxLen  = '_id'.length;
            for (let i = 0; i < nestedNode.children.length; i++) {
                const child = nestedNode.children[i];
                if (child.children.length > 0 || child.refId() !== null) continue;
                const len = child.parseName().length;
                if (len > nestedMaxLen) nestedMaxLen = len;
            }
            const nestedFkCols: Record<string, boolean> = {};
            if (nestedNode.fks !== null) for (const fk in nestedNode.fks) nestedFkCols[fk] = true;

            const open  = isChild ? '[{\n' : '{\n';
            const close = isChild ? '}]'   : '}';

            ret += tab + nestedName + ' '.repeat(rootMaxLen - nestedName.length) + ' : ' + this._ddl.objPrefix() + nestedNode.parseName() + ' ' + annotations + '\n';
            ret += tab + open;
            ret += tab + tab + '_id' + ' '.repeat(nestedMaxLen - '_id'.length) + ' : ' + nestedPkCol + ',\n';
            for (const child of nestedNode.regularColumns()) {
                const cname = child.parseName();
                if (cname === nestedPkCol || nestedFkCols[cname]) continue;
                ret += tab + tab + cname + ' '.repeat(nestedMaxLen - cname.length) + ' : ' + cname + ',\n';
            }
            ret = ret.replace(/,\n$/, '\n');
            ret += tab + close + ',\n';
        }

        ret = ret.replace(/,\n$/, '\n');
        ret += '};\n\n';
        return ret.toLowerCase();
    }

    generateTransTable(node: DdlNode): string {
        if (node.inferType() !== 'table') return '';
        const transCols = node.getTransColumns();
        if (transCols.length === 0) return '';

        const objName   = this._ddl.objPrefix() + node.parseName();
        const transName = objName + '_trans';
        const char      = this._ddl.semantics();

        let maxLen     = 'language_code'.length;
        const fkColName = (singular(node.parseName()) ?? node.parseName()) + '_id';
        if (fkColName.length > maxLen) maxLen = fkColName.length;
        for (let i = 0; i < transCols.length; i++) {
            const colName = 'trans_' + transCols[i].parseName();
            if (colName.length > maxLen) maxLen = colName.length;
        }
        if ('id'.length > maxLen) maxLen = 'id'.length;

        let ret = 'create table ' + transName + ' (\n';
        let pad = tab + ' '.repeat(maxLen - 'id'.length);
        ret += tab + 'id' + pad + 'number ' + this._pkTypeModifier(transName) + '\n';
        ret += tab + tab + ' '.repeat(maxLen) + 'constraint ' + transName + '_id' + this._naming.pk + ' primary key,\n';

        pad = tab + ' '.repeat(maxLen - fkColName.length);
        ret += tab + fkColName + pad + 'number not null,\n';

        pad = tab + ' '.repeat(maxLen - 'language_code'.length);
        ret += tab + 'language_code' + pad + `varchar2(5${char}) not null,\n`;

        for (let i = 0; i < transCols.length; i++) {
            const colName = 'trans_' + transCols[i].parseName();
            pad = tab + ' '.repeat(maxLen - colName.length);
            const baseType = this._toOracleType(transCols[i]._inferTypeFull());
            ret += tab + colName + pad + baseType + ',\n';
        }
        ret += tab + 'constraint ' + transName + this._naming.uk + ' unique (' + fkColName + ', language_code)\n';
        ret += ');\n\n';

        let abbrev = node.parseName();
        if (abbrev.length > 2) abbrev = abbrev.substring(0, 2);
        ret += 'alter table ' + transName + ' add constraint ' + transName + '_' + abbrev + '_id' + this._naming.fk + '\n';
        ret += tab + 'foreign key (' + fkColName + ') references ' + objName + ';\n\n';
        ret += 'alter table ' + transName + ' add constraint ' + transName + '_lang' + this._naming.fk + '\n';
        ret += tab + 'foreign key (language_code) references ' + this._ddl.objPrefix() + 'language (code);\n\n';
        ret += 'create index ' + transName + this._naming.idx + '1 on ' + transName + ' (' + fkColName + ');\n';
        ret += 'create index ' + transName + this._naming.idx + '2 on ' + transName + ' (language_code);\n\n';
        return ret;
    }

    generateResolvedView(node: DdlNode): string {
        if (node.inferType() !== 'table') return '';
        const transCols = node.getTransColumns();
        if (transCols.length === 0) return '';

        const objName       = this._ddl.objPrefix() + node.parseName();
        const transName     = objName + '_trans';
        const viewName      = objName + '_resolved';
        const fkColName     = (singular(node.parseName()) ?? node.parseName()) + '_id';
        const transContext  = this._ddl.getOptionValue('transcontext');

        let ret = 'create or replace view ' + viewName + ' as\nselect ';
        const selectCols: string[] = [];

        const idColName = node.getPkName();
        if (idColName !== null) selectCols.push('k.' + idColName);

        node.lateInitFks();
        for (const fk in node.fks) {
            if (0 < fk.indexOf(',')) continue;
            const refNode = this._ddl.find(node.fks![fk]);
            let _id = '';
            if (refNode !== null && refNode.isMany2One && refNode.isMany2One() && !fk.endsWith('_id')) _id = '_id';
            selectCols.push('k.' + fk + _id);
        }

        const transColNames: Record<string, boolean> = {};
        for (let i = 0; i < transCols.length; i++) transColNames[transCols[i].parseName()] = true;

        for (const child of node.regularColumns()) {
            const cname = child.parseName();
            if (idColName !== null && cname === 'id') continue;
            if (cname === node.getExplicitPkName()) continue;
            if (transColNames[cname])
                selectCols.push('coalesce(t.trans_' + cname + ', k.' + cname + ') as ' + cname);
            else
                selectCols.push('k.' + cname);
        }

        ret += selectCols[0] + ',\n';
        for (let i = 1; i < selectCols.length; i++) {
            ret += tab + tab + ' ' + selectCols[i];
            if (i < selectCols.length - 1) ret += ',';
            ret += '\n';
        }
        ret += 'from ' + objName + ' k\n';
        ret += 'left join ' + transName + ' t\n';
        ret += tab + 'on t.' + fkColName + ' = k.' + (idColName ?? node.getExplicitPkName()) + '\n';
        ret += tab + 'and t.language_code = ' + transContext + ';\n\n';
        return ret;
    }

    generateERD(): ErdOutput {
        const descendants = this._ddl.descendants() as DdlNode[];
        const output: ErdOutput = { items: [], links: [] };

        for (const node of descendants) {
            if (node.inferType() !== 'table') continue;

            const item: ErdItem = {
                name:    this._ddl.objPrefix('no schema') + node.parseName(),
                schema:  (this._ddl.getOptionValue('schema') as string) || null,
                columns: [],
            };
            output.items.push(item);

            // PK column
            const idColName = node.getGenIdColName();
            if (idColName != null && !node.isOption('pk')) {
                item.columns.push({ name: idColName, datatype: 'number' });
            } else {
                const pkName = node.getExplicitPkName();
                if (pkName != null && !pkName.includes(',')) {
                    const child = node.findChild(pkName);
                    item.columns.push({ name: pkName, datatype: child ? this._toOracleType(child._inferTypeFull()) : 'number' });
                }
            }

            // FK columns
            node.lateInitFks();
            for (const fk in node.fks) {
                const parent: string = node.fks[fk];
                if (fk.includes(',')) {
                    const refNode = this._ddl.find(parent);
                    const chunks  = split_str(fk, ', ');
                    for (const col of chunks) {
                        if (col === ',') continue;
                        const pChild = refNode?.findChild(col);
                        item.columns.push({ name: col, datatype: pChild ? this._toOracleType(pChild._inferTypeFull()) : 'number' } as ErdColumn);
                    }
                    continue;
                }
                const attr    = node.findChild(fk);
                let   type    = attr ? attr.inferType() : 'number';
                let   fkName  = fk;
                const refNode = this._ddl.find(parent);
                if (refNode != null) {
                    type = this._fkOracleType(refNode) ?? type;
                } else {
                    const altRef = this._ddl.find(fk);
                    if (altRef?.isMany2One?.() && !fk.endsWith('_id'))
                        fkName = (singular(fk) ?? fk) + '_id';
                }
                item.columns.push({ name: fkName, datatype: type });
            }

            // Regular columns
            const explicitPk = node.getExplicitPkName();
            for (const child of node.children) {
                if (child.inferType() === 'table') continue;
                if (child.refId()     != null)     continue;
                if (child.parseName() === explicitPk) continue;
                item.columns.push({ name: child.parseName(), datatype: this._toOracleType(child._inferTypeFull()) });
                if (child.indexOf('file') > 0) {
                    const col = child.parseName();
                    item.columns.push({ name: col + '_filename', datatype: 'varchar2(255' + this._ddl.semantics() + ')' });
                    item.columns.push({ name: col + '_mimetype', datatype: 'varchar2(255' + this._ddl.semantics() + ')' });
                    item.columns.push({ name: col + '_charset',  datatype: 'varchar2(255' + this._ddl.semantics() + ')' });
                    item.columns.push({ name: col + '_lastupd',  datatype: 'date' });
                }
            }

            // Row meta-columns
            const nodeContent = node.trimmedContent().toUpperCase() as string;
            if (this._ddl.optionEQvalue('rowkey', true) || nodeContent.includes('/ROWKEY'))
                item.columns.push({ name: 'row_key', datatype: 'varchar2(30' + this._ddl.semantics() + ')' });
            if (this._ddl.optionEQvalue('rowVersion', 'yes') || nodeContent.includes('/ROWVERSION'))
                item.columns.push({ name: 'row_version', datatype: 'integer' });
            if (this._ddl.optionEQvalue('Audit Columns', 'yes') || nodeContent.includes('/AUDITCOLS')) {
                let auditType = (this._ddl.getOptionValue('auditdate') as string | null) || '';
                if (!auditType) auditType = this._ddl.getOptionValue('Date Data Type') as string;
                auditType = auditType.toLowerCase();
                const char = this._ddl.semantics();
                item.columns.push({ name: this._ddl.getOptionValue('createdcol')   as string, datatype: auditType });
                item.columns.push({ name: this._ddl.getOptionValue('createdbycol') as string, datatype: 'varchar2(255' + char + ')' });
                item.columns.push({ name: this._ddl.getOptionValue('updatedcol')   as string, datatype: auditType });
                item.columns.push({ name: this._ddl.getOptionValue('updatedbycol') as string, datatype: 'varchar2(255' + char + ')' });
            }
        }

        // Links
        for (const node of descendants) {
            if (node.inferType() !== 'table') continue;
            this.generateDDL(node);  // populates node.fks as side-effect
            for (const fk in node.fks) {
                const parent  = node.fks[fk];
                const pkNode  = this._ddl.find(parent);
                if (pkNode == null) continue;
                const pk        = pkNode.getExplicitPkName() ?? 'id';
                const fkAttr    = node.findChild(fk);
                const mandatory = fkAttr == null || fkAttr.isOption('nn') || fkAttr.isOption('notnull');
                const link: ErdLink = {
                    source:    this._ddl.objPrefix() + parent,
                    source_id: pk,
                    target:    this._ddl.objPrefix() + node.parseName(),
                    target_id: fk,
                };
                if (mandatory) link.mandatory = mandatory;
                output.links.push(link);
            }
        }

        // Groups (only include when non-empty)
        const groups: Record<string, string[]> = {};
        for (const node of descendants) {
            if (node.inferType() !== 'table') continue;
            const groupName = node.getAnnotationValue('TGROUP') as string | null;
            if (groupName != null) {
                if (!groups[groupName]) groups[groupName] = [];
                groups[groupName].push(this._ddl.objPrefix('no schema') + node.parseName());
            }
        }
        if (Object.keys(groups).length > 0) output.groups = groups;

        return output;
    }

    generateFullDDL(): string {
        const forest      = this._ddl.forest      as DdlNode[];
        const descendants = this._ddl.descendants() as DdlNode[];
        let   output      = '';

        // DROP statements
        if (this._ddl.optionEQvalue('Include Drops', 'yes'))
            for (const node of descendants) {
                const drop = this.generateDrop(node);
                if (drop) output += drop;
            }

        // Row-key sequence
        if (this._ddl.optionEQvalue('rowkey', true)) {
            output += 'create sequence  row_key_seq;\n\n';
        } else {
            for (const root of forest) {
                if (root.trimmedContent().toUpperCase().includes('/ROWKEY')) {
                    output += 'create sequence  row_key_seq;\n\n';
                    break;
                }
            }
        }

        // Tables
        output += '-- create tables\n\n';
        for (const root of forest)
            output += this.generateDDL(root) + '\n';
        for (const alter of this._ddl.postponedAlters)
            output += alter + '\n';

        // Translation tables
        const hasTransCols = descendants.some(n => n.getTransColumns().length > 0);
        if (hasTransCols) {
            const char = this._ddl.semantics();
            const p    = this._ddl.objPrefix();
            output += '-- translation support\n\n';
            output += `create table ${p}language (\n`;
            output += `    code           varchar2(5${char}) not null\n`;
            output += `                   constraint ${p}language_code_pk primary key,\n`;
            output += `    locale         varchar2(28${char}) not null\n`;
            output += `                   constraint ${p}language_locale_unq unique,\n`;
            output += `    name           varchar2(1024${char}),\n`;
            output += `    native_name    varchar2(1024${char})\n`;
            output += `);\n\n`;
            output += `create index ${p}language_i1 on ${p}language (locale);\n\n`;
            for (const node of descendants) {
                const t = this.generateTransTable(node);
                if (t) output += t;
            }
        }

        // Triggers
        let j = 0;
        for (const node of descendants) {
            const trigger = this.generateTrigger(node);
            if (trigger) { if (j++ === 0) output += '-- triggers\n'; output += trigger + '\n'; }
        }
        for (const node of descendants) {
            const trigger = this.generateImmutableTrigger(node);
            if (trigger) { if (j++ === 0) output += '-- immutable triggers\n'; output += trigger; }
        }

        // ORDS REST enable
        for (const node of descendants) {
            const ords = this.restEnable(node);
            if (ords) output += ords + '\n';
        }

        // TAPI
        j = 0;
        for (const node of descendants) {
            if (this._ddl.optionEQvalue('api', false) &&
                !node.trimmedContent().toLowerCase().includes('/api'))
                continue;
            const tapi = this.generateTAPI(node);
            if (tapi) { if (j++ === 0) output += '-- APIs\n'; output += tapi + '\n'; }
        }

        // Views
        j = 0;
        for (const root of forest) {
            const view = this.generateView(root);
            if (view) { if (j++ === 0) output += '-- create views\n'; output += view + '\n'; }
        }
        for (const node of descendants) {
            const rv = this.generateResolvedView(node);
            if (rv) { if (j++ === 0) output += '-- create views\n'; output += rv; }
        }

        // Table groups (TGROUP annotation)
        const groups: Record<string, string[]> = {};
        for (const node of descendants) {
            if (node.inferType() !== 'table') continue;
            const groupName = node.getAnnotationValue('TGROUP');
            if (groupName != null) {
                if (!groups[groupName]) groups[groupName] = [];
                groups[groupName].push(this._ddl.objPrefix() + node.parseName());
            }
        }
        const groupNames = Object.keys(groups);
        if (groupNames.length > 0) {
            output += '-- table groups\n';
            for (const gn of groupNames) {
                output += `insert into user_annotations_groups$ (group_name) values ('${gn}');\n`;
                for (const member of groups[gn])
                    output += `insert into user_annotations_group_members$ (group_name, object_name) values ('${gn}', '${member.toUpperCase()}');\n`;
            }
            output += '\n';
        }

        // AI enrichment (db >= 26)
        const enrichDbVer = this._ddl.getOptionValue('db') as string | null;
        if (this._ddl.optionEQvalue('aienrichment', true) &&
            enrichDbVer != null && enrichDbVer.length >= 2 &&
            (getMajorVersion(enrichDbVer) ?? 0) >= 26) {
            const enrichCalls:  string[] = [];
            const enrichGroups: Record<string, string[]> = {};
            const prefix = this._ddl.objPrefix();

            for (const node of forest) {
                const type    = node.inferType();
                const pairs   = node.getAnnotationPairs();
                const objName = (prefix + node.parseName()).toUpperCase();

                if (type === 'table') {
                    for (const pair of pairs) {
                        if (pair.label.toUpperCase() === 'TGROUP') {
                            if (pair.value != null) {
                                if (!enrichGroups[pair.value]) enrichGroups[pair.value] = [];
                                enrichGroups[pair.value].push(objName);
                            }
                            continue;
                        }
                        if (pair.value == null) continue;
                        enrichCalls.push(`    metadata_annotations.set('${pair.label}', '${pair.value}', '${objName}');`);
                    }
                    for (const col of node.children) {
                        if (col.children.length > 0) continue;
                        const colPairs = col.getAnnotationPairs();
                        const colName  = objName + '.' + col.parseName().toUpperCase();
                        for (const pair of colPairs) {
                            if (pair.value == null) continue;
                            enrichCalls.push(`    metadata_annotations.set('${pair.label}', '${pair.value}', '${colName}', 'TABLE COLUMN');`);
                        }
                    }
                } else if (type === 'view') {
                    for (const pair of pairs) {
                        if (pair.value == null) continue;
                        enrichCalls.push(`    metadata_annotations.set('${pair.label}', '${pair.value}', '${objName}', 'VIEW');`);
                    }
                }
            }

            for (const gn of Object.keys(enrichGroups)) {
                enrichCalls.push(`    metadata_annotations.create_group('${gn}');`);
                for (const member of enrichGroups[gn])
                    enrichCalls.push(`    metadata_annotations.add_to_group('${gn}', '${member}', 'TABLE');`);
            }

            if (enrichCalls.length > 0)
                output += '-- AI enrichment\nbegin\n' + enrichCalls.join('\n') + '\nend;\n/\n\n';
        }

        // Sample data
        j = 0;
        for (const root of forest) {
            const data = this.generateData(root, this._ddl.data);
            if (data) { if (j++ === 0) output += '-- load data\n\n'; output += data + '\n'; }
        }

        return output;
    }
}

// ── Generator factory ─────────────────────────────────────────────────────────

