import { getMajorVersion } from './naming.js';
import type { DdlContext, SemanticType } from './types.js';
import type { Naming } from './node.js';

// ── Oracle type rendering ─────────────────────────────────────────────────────

const IDENTITY_MODIFIER_LOWER = 'generated by default on null as identity';

/**
 * Map a SemanticType to an Oracle DDL column type string.
 * Pure function: no context access, easy to test in isolation.
 */
export function toOracleType(sem: SemanticType, semantics: string, db23: boolean): string {
    switch (sem.base) {
        case 'varchar':   return `varchar2(${sem.varcharLen ?? 4000}${semantics})`;
        case 'number':    return sem.numericSpec ? `number${sem.numericSpec}` : 'number';
        case 'integer':   return 'integer';
        case 'date':      return 'date';
        case 'timestamp': return 'timestamp';
        case 'tswtz':     return 'timestamp with time zone';
        case 'tswltz':    return 'timestamp with local time zone';
        case 'clob':      return 'clob';
        case 'blob':      return 'blob';
        case 'boolean':   return 'boolean';
        case 'geometry':  return 'sdo_geometry';
        case 'json':      return db23 ? 'json' : `clob check (${sem.colName} is json)`;
        case 'vector':    return `vector${sem.vectorSpec ?? '(*,*,*)'}`;
        default:          return sem.base;
    }
}

/** Resolve the db23 flag from a DdlContext. */
export function isDb23(ctx: DdlContext): boolean {
    const v = ctx.getOptionValue('db') as string | null;
    return v != null && v.length > 0 && 23 <= (getMajorVersion(v) ?? 0);
}

/**
 * Return the PK column modifier clause for Oracle tables/sequences.
 * Used by both table DDL and the translation-table generator.
 */
export function oraclePkTypeModifier(
    objName: string, ctx: DdlContext, naming: Naming,
): string {
    if (ctx.optionEQvalue('pk', 'identityDataType')) return IDENTITY_MODIFIER_LOWER;
    if (ctx.optionEQvalue('pk', 'seq'))
        return ('default on null ' + objName + naming.seq + '.NEXTVAL ').toLowerCase();
    if (ctx.optionEQvalue('pk', 'guid'))
        return "default on null to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') ";
    return 'not null';
}
