/**
 * Integration tests for specific DDL behaviors.
 * Ported from small_tests.js — each assertion group becomes a named test case.
 * Organized by feature area, not by bug number.
 */
import { describe, test, expect, beforeEach } from 'vitest';
import quicksql, { toDDL }  from '../../src/ddl.js';
import { resetSeed }         from '../../src/sample.js';

beforeEach(() => { resetSeed(); });

function ddl(input: string, opts?: string): string {
    return new (quicksql as any)(input, opts).getDDL();
}

// ── Settings ──────────────────────────────────────────────────────────────────

describe('settings', () => {

    test('inline #settings takes precedence over constructor parameter', () => {
        const out = toDDL(
            `departments\n    name\n# settings = {"prefix": "RIGHT"}`,
            '{"prefix": "WRONG"}'
        );
        expect(out).toContain('create table right_departments');
    });

    test('unknown setting in constructor parameter raises error message', () => {
        const out = ddl(`Bug35683432\n    name`, '{"notAnOption1": "should raise an Error"}');
        expect(out).toContain('Unknown setting: notanoption1');
    });

    test('unknown setting in inline #settings raises error message', () => {
        const out = ddl(`Bug35683432\n    name\n# settings = {"notAnOption2": "should raise an Error"}`);
        expect(out).toContain('Unknown setting: notanoption2');
    });

    test('overrideSettings prevents parameter from overriding inline settings', () => {
        const out = ddl(
            `Bug35757000\n    name\n# settings = {"overrideSettings":"true"}`,
            '{"prefix":"X"}'
        );
        expect(out).not.toContain('x_');
    });

    test('non-default options appear in output once only', () => {
        const out = ddl(
            `Bug35650456_2\n    job vc5000\n--- Non-default options:\n# settings = {"apex":"Y","db":"19c","longvc":"N"}`
        );
        expect(out.indexOf('Non-default options')).toBe(out.lastIndexOf('Non-default options'));
    });

    test('prefix with trailing underscore does not double the underscore', () => {
        const out = ddl(`dept\n    dname\n# settings = {"prefix": "abc_"}`);
        expect(out).toContain('abc_dept');
        expect(out).not.toContain('abc__dept');
    });

    test('schema + prefix do not generate schema.prefix_id_pk', () => {
        const out = ddl(`dept\n    name\n# settings = {prefix: "prefix", schema: "schema"}`);
        expect(out).not.toContain('schema.prefix_dept_id_pk');
    });

});

// ── Primary keys ──────────────────────────────────────────────────────────────

describe('primary keys', () => {

    test('genpk:false removes identity column', () => {
        const out = ddl(`departments\n    name\n# settings = {"genpk": false}`);
        expect(out.toLowerCase()).not.toContain('id     number generated');
    });

    test('genpk:false via constructor option', () => {
        const out = ddl(`departments\n    name`, '{ "genpk": false }');
        expect(out.toLowerCase()).not.toContain('id     number generated');
    });

    test('pk:NONE — no trigger, explicit PK constraint kept', () => {
        const out = ddl(`bug35748389\n    name\n# settings = {"pk":"NONE"}`);
        expect(out).not.toContain('trigger');
        expect(out).toContain('constraint bug35748389_id_pk primary key,');
    });

    test('pk:SEQ — no trigger, nextval default', () => {
        const out = ddl(`bug35748389_2\n    name\n# settings = {"pk":"seq"}`);
        expect(out).not.toContain('trigger');
        expect(out).toContain('number default on null bug35748389_2_seq.nextval');
        expect(out).toContain('constraint bug35748389_2_id_pk primary key,');
    });

    test('pk:IDENTITY — no trigger, GENERATED BY DEFAULT ON NULL AS IDENTITY', () => {
        const out = ddl(`bug35748389_4\n    name\n# settings = {"pk":"identity"}`);
        expect(out).not.toContain('trigger');
        expect(out).toContain('number generated by default on null as identity');
        expect(out).toContain('constraint bug35748389_4_id_pk primary key,');
    });

    test('genpk:false — no id column at all', () => {
        const out = ddl(`bug35748389_3\n    name\n# settings = {"genpk":false}`);
        expect(out).not.toContain('trigger');
        expect(out).not.toContain('id');
    });

    test('pk:GUID — number with to_number(sys_guid())', () => {
        const out = ddl(`dept\n     dname`);
        expect(out).toContain('number default on null to_number(sys_guid()');
    });

    test('composite PK via /pk col1, col2 — no auto id', () => {
        const out = ddl(`employee /pk first_name, last_name\n    first_name\n    last name\n    job history\n        start_date\n        end_date`);
        expect(out).not.toContain('employee_id');
        expect(out).toContain('alter table employee add constraint employee_pk primary key (first_name,last_name);');
        expect(out).toContain('constraint employee_job_history_fk foreign key (first_name,last_name) references employee;');
    });

    test('composite UK via /UK col1, col2', () => {
        const out = ddl(`employee /UK first_name, last_name\n    first_name\n    last_name`);
        expect(out).toContain('alter table employee add constraint employee_uk unique (first_name,last_name);');
    });

    test('explicit PK column overrides auto id', () => {
        const out = ddl(`person\n    id num /pk\n    name vc40\n    date_of_birth date\n    mother /fk person\n    father /fk person`);
        expect(out).toContain('id               number');
        expect(out).toContain('person_id_pk primary key');
    });

    test('custom PK column name keeps PK constraint', () => {
        const out = ddl(`countries\n    code vc2 /pk`);
        expect(out).toContain('code    varchar2(2 char) not null');
    });

    test('explicit PK column named after table_id', () => {
        const out = ddl(`countries\n    country_id vc2 /pk`);
        expect(out).toContain('country_id    varchar2(2 char) not null');
    });

    test('pk:SEQ — drop sequence included when drop:Y', () => {
        const out = ddl(`# pk: SEQ\n# drop: Y\nstudents\n    name`);
        expect(out).toContain('drop sequence students_seq');
    });

    test('pk:SEQ — on custom pk column', () => {
        const out = ddl(`customers\n    cid /pk\n#settings = { pk: "SEQ"}`);
        expect(out).toContain('cid    number default on null customers_seq.nextval');
        expect(out).not.toContain('trigger');
    });

    test('pk:GUID — no trigger or alter', () => {
        const out = ddl(`# settings = {"pk":"GUID"}\nstudents /insert 2\n    name`);
        expect(out).not.toContain('trigger');
        expect(out).not.toContain('alter');
    });

    test('existing id column is not duplicated', () => {
        const out = ddl(`customers\n    id`);
        expect(out).not.toContain('id    varchar2');
    });

    test('prefixPKwithTname:true applies prefix to PK column names', () => {
        const out = ddl(`# settings = {prefixPKwithTname:true, "api":"Y"}\nperson\n    first_name\n    last_name\n    first_date\naddreess\n    address1\n    address2\n    person_id`);
        expect(out).not.toContain('p_id');
    });

});

// ── Data types ────────────────────────────────────────────────────────────────

describe('data types', () => {

    test('vc32k → varchar2(32767 char)', () => {
        const out = ddl(`Bug35650456\n    name  vc32k`);
        expect(out).toContain('name    varchar2(32767 char)');
    });

    test('vc (no size) → varchar2(4000', () => {
        const out = ddl(`Bug35827840\n    col1 vc`);
        expect(out).toContain('col1    varchar2(4000');
    });

    test('string/varchar/varchar2/char → mapped correctly', () => {
        const out = ddl(`Bug35827927\n    colstr string\n    colvarchar varchar\n    colvarchar2 varchar2\n    colchar char`);
        expect(out).toContain('colstr    ');
        expect(out).toContain('colvarchar    ');
        expect(out).toContain('colvarchar2    varchar2(4000');
        expect(out).toContain('colchar    ');
    });

    test('timestamp, tstz, tswltz mapped correctly', () => {
        const out = ddl(`Bugs35692739\n    date_creation timestamp\n    date_packed tstz\n    date_production timestamp with local time zone`);
        expect(out).toContain('date_creation      timestamp,');
        expect(out).toContain('date_packed        timestamp with time zone,');
        expect(out).toContain('date_production    timestamp with local time zone');
    });

    test('json column → clob check (... is json) on db < 23', () => {
        const out = ddl(`Bug35692739_json\n    flight_json json`);
        expect(out).toContain('clob check (flight_json is json)');
    });

    test('file column → file_name, file_mimetype, etc.', () => {
        const out = ddl(`Bug35737578\n    flight_file file`);
        expect(out).toContain('flight_file_filename');
    });

    test('file column names do not bleed into other columns', () => {
        const out = ddl(`Bug35757130\n    file_name vc(512)\n    file_mimetype vc(512)\n    file_charset vc(512)\n    file_lastupd date\n    file_blob blob\n    file_comments vc(4000)\n    tags`);
        expect(out).toContain('file_name        varchar2(512 char),');
        expect(out).not.toContain('file_mimetype_mimetype');
        expect(out).not.toContain('file_lastupd_filename');
    });

    test('bool/yn column → varchar2(1) with check constraint', () => {
        const out = ddl(`Bug35814922\n    important_yn\n    important1 yn\n    important2 bool\n    is_important`);
        expect(out).toContain("important_yn    varchar2(1");
        expect(out).toContain('constraint bug35814922_important_yn');
        expect(out).toContain("important1      varchar2(1");
        expect(out).toContain("important2      varchar2(1");
        expect(out).toContain("is_important    varchar2(1");
    });

    test('/boolean directive with /default y', () => {
        const out = ddl(`foo\n    bar /boolean /default y`);
        expect(out).toContain("varchar2(1 char) default on null 'y'");
        expect(out).toContain("constraint foo_bar check (bar in ('Y','N'))");
    });

    test('/default with sysdate/systimestamp is not quoted', () => {
        const out = ddl(`queues\n    created /default sysdate\n    created_dt /default systimestamp`);
        expect(out).toContain('default on null sysdate');
        expect(out).toContain('default on null systimestamp');
    });

    test('/default current_timestamp and localtimestamp are not quoted', () => {
        const out = ddl(`events\n    created_at ts /default current_timestamp\n    modified_at ts /default systimestamp\n    regular_col vc(20) /default hello`);
        expect(out).toContain('default on null current_timestamp');
        expect(out).toContain('default on null systimestamp');
        expect(out).toContain("default on null 'hello'");
    });

    test('/default boolean N maps to false on db >= 23', () => {
        const out = ddl(`test\n    flag_yn boolean /default N\n# settings = {"db":"23ai","pk":"IDENTITY"}`);
        expect(out).toContain('boolean default on null false');
    });

    test('geometry column → sdo_geometry + spatial index', () => {
        const out = ddl(`addresses\n    street_name\n    location geometry`);
        expect(out).toContain('sdo_geometry');
        expect(out).toContain('indextype is mdsys.spatial_index_v2');
    });

});

// ── Constraints and directives ────────────────────────────────────────────────

describe('constraints and directives', () => {

    test('/cascade generates ON DELETE CASCADE FK', () => {
        const out = ddl(`dept\n    dname\n    emp /cascade\n        dept_id\n        ename`);
        expect(out).toContain('dept_id    number');
        expect(out).toContain('constraint emp_dept_id_fk');
        expect(out).toContain('references dept on delete cascade');
    });

    test('/setnull generates ON DELETE SET NULL FK', () => {
        const out = ddl(`dept\n    dname\n    emp /setnull\n        dept_id\n        ename`);
        expect(out).toContain('dept_id    number');
        expect(out).toContain('constraint emp_dept_id_fk');
        expect(out).toContain('references dept on delete set null');
    });

    test('/cascade on child table column', () => {
        const out = ddl(`dept\n    dname\n    emp /cascade\n        dept_id\n        ename`);
        expect(out).toContain('constraint emp_dept_id_fk');
        expect(out).toContain('references dept on delete cascade,');
        expect(out).not.toContain('dept_id    integer');
    });

    test('department_id column is not duplicated when child references parent', () => {
        const out = ddl(`departments\n    dname\n    emp\n        department_id /fk departments\n        ename`);
        expect(out.indexOf('department_id    number')).toBe(out.lastIndexOf('department_id    number'));
    });

    test('/nn on non-pk column', () => {
        const out = ddl(`countries\n    code vc2 /pk`);
        expect(out).toContain('code    varchar2(2 char) not null');
    });

    test('/check with quoted values', () => {
        const out = ddl(`Bug35714241\n    proficiency /check 'Test'`);
        expect(out).toContain("in ('Test'");
    });

    test('/check with backtick literals (no double-escaping)', () => {
        const out = ddl("escape /insert 1\n    financial_year /check '23/24', `'24/25'`\n    surname vc60 /check 'O''Hara', q'{O'Tool}'\n    start_date /check `to_date('01-APR-2025','DD-MON-YYYY')`");
        expect(out).toContain("check (financial_year in ('23/24','24/25')),");
        expect(out).toContain("check (surname in ('O''Hara',q'{O'Tool}')),");
        expect(out).toContain("check (start_date in (to_date('01-APR-2025','DD-MON-YYYY')))");
        expect(out).not.toContain("''24/25''");
        expect(out).not.toContain("q''{O''Tool}''");
        expect(out).not.toContain("to_date(''01-APR-2025'',''DD-MON-YYYY'')");
    });

    test('vc(255) maps to varchar2(255 char)', () => {
        const out = ddl(`Bugs35692739\n    description vc(255)`);
        expect(out).toContain('varchar2(255 char)');
    });

    test('/data_type check with comma-separated values', () => {
        const out = ddl(`change_history\n    data_type vc20 /check VARCHAR2,CLOB,TSWLTZ`);
        expect(out).toContain('data_type    varchar2(20');
    });

    test('/domain directive applies domain type on db >= 23', () => {
        const out = ddl(`users\n    email /domain email_d /nn\n    phone /domain phone_d\n# settings = {"db":"23ai"}`);
        expect(out).toContain('email_d not null');
        expect(out).toContain('phone_d');
    });

    test('/domain directive ignored on db < 23', () => {
        const out = ddl(`users2\n    email /domain email_d\n# settings = {"db":"19c"}`);
        expect(out).toContain('varchar2');
        expect(out).toContain('email    varchar2');
    });

    test('int type preserves integer datatype', () => {
        const out = ddl(`test\n    foo_id int /nn /fk foo`);
        expect(out).toContain('foo_id    integer');
    });

});

// ── Inserts ───────────────────────────────────────────────────────────────────

describe('inserts', () => {

    test('inserts:false suppresses INSERT statements', () => {
        const out = ddl(`Bug35683307 /insert 1\n  # settings = { inserts: false}`);
        expect(out).not.toContain('insert into');
    });

    test('# inserts : N line not duplicated in output', () => {
        const out = ddl(`dept /insert 5\n    name\n# inserts : N`, '{"inserts":"N"}');
        expect(out).not.toContain('# inserts : N');
    });

    test('insert with prefix uses prefixed table name', () => {
        const out = ddl(`departments /insert 1\n    name /nn\n# settings = {"prefix":"test"}`);
        expect(out).toContain('insert into test_departments (');
    });

    test('date columns in inserts do not produce N/A', () => {
        const out = ddl(`employees /insert 1\n   date hired\n#settings={ date:timestamp}`);
        expect(out).not.toContain('N/A');
    });

    test('insert description column respects vc length', () => {
        const out = ddl(`reports /insert 1\n   created date\n   description vc20\n   pdf blob`);
        const trimmed = out.substring(0, out.indexOf('-- Generated by Radicle QuickSQL'));
        expect(trimmed).not.toContain('N/A');
        const src = (quicksql as any).lexer(trimmed, false, true, '`');
        expect((src[56] as any).value.length).toBeLessThanOrEqual(22);  // vc20 + 2 quotes
    });

    test('insert generates different names for different rows', () => {
        resetSeed();
        const out = ddl(`issue78 /insert 2\n    name`);
        expect(out).toContain('Landon Glover');
        expect(out).toContain('Jack Jackson');
    });

});

// ── API / audit / compress ────────────────────────────────────────────────────

describe('api, audit, compress', () => {

    test('api:true generates ORDS handler', () => {
        const out = ddl(`departments\n    name\n# settings = { "api": true }`, '{ "api": false }');
        expect(out.toLowerCase()).toContain('departments_api');
    });

    test('auditcols:true with apex:false uses :user not APEX$SESSION', () => {
        const out = ddl(
            `Bug35737917 /auditcols\n    name\n# settings = {"apex":"false"}`,
            '{"apex":"true"}'
        );
        expect(out).toContain(':new.created_by := user;');
        expect(out).not.toContain('APEX$SESSION');
    });

    test('/audit cols and /audit columns are synonyms', () => {
        const out = ddl(`departments /audit cols\n   name\n   employees /audit columns\n       name`);
        expect(out).toContain('department_id');
        expect(out).not.toContain('audit all');
        expect(out.indexOf('created       date not null')).toBeLessThan(out.lastIndexOf('created          date not null,'));
    });

    test('compress:yes generates ) compress;', () => {
        const out = ddl(`departments\n    name\n# settings = { "Compress": "yEs" }`);
        expect(out).toContain(') compress;');
    });

    test('colprefix adds prefix to all column names', () => {
        const out = ddl(`test /insert 1 /colprefix pre\n   t1\n#drop:true`);
        const trimmed = out.substring(0, out.indexOf('-- Generated by Radicle QuickSQL'));
        expect(trimmed).toContain('pre_t1');
        expect(trimmed).not.toContain(' t1');
    });

});

// ── Views ─────────────────────────────────────────────────────────────────────

describe('views', () => {

    test('basic view references correct table name with prefix', () => {
        const out = ddl(`dept\n    name\nview v dept\n# settings = {prefix: "abc"}`);
        expect(out.indexOf('from')).toBeLessThan(out.lastIndexOf('abc_dept'));
    });

    test('view column aliases do not leak slash chars', () => {
        const out = ddl(`departments\n    name\n    employees\n       name\nview emp_v departments employees`);
        const trimmed = out.substring(0, out.indexOf('-- Generated by Radicle QuickSQL'));
        expect(trimmed).not.toContain('departments.id/');
    });

    test('reserved word user gets the_ prefix in view alias', () => {
        const out = ddl(`# settings = {"prefix":"IW","pk":"IDENTITY"}\nuser\n    username vc(50)\ntask\n    user_id /fk user\nview task_v task user`);
        expect(out).toContain('iw_user the_user');
        expect(out).toContain('the_user.id');
        expect(out).toContain('the_user.username');
    });

    test('view FROM clause has space between table name and alias', () => {
        const out = ddl(`# settings = {"prefix":"IW","pk":"IDENTITY"}\ndept\n    name\nview dept_v dept`);
        expect(out).toContain('iw_dept dept');
        expect(out).not.toContain('iw_deptdept');
    });

    test('view WHERE clause uses actual FK column name', () => {
        const out = ddl(`# settings = {"prefix":"IW","pk":"IDENTITY"}\nuser\n    username vc(50)\nvisit\n    planned_by /fk user\nview stats_v visit user`);
        expect(out).toContain('left join');
        expect(out).toContain('on visit.planned_by = the_user.id');
        expect(out).not.toContain('(+)');
    });

    test('duplicate column aliases are disambiguated in view', () => {
        const out = ddl(`# settings = {"prefix":"IW","pk":"IDENTITY"}\nuser\n    username vc(50)\nauth\n    user_id /fk user\nview auth_v user auth`);
        expect(out).toContain('auth_user_id');
    });

    test('view without /trans has no LEFT JOIN', () => {
        const out = ddl(`dept\n    name\nview dept_v dept`);
        expect(out).not.toContain('left join');
        expect(out).not.toContain('coalesce');
    });

});

// ── Reserved words ────────────────────────────────────────────────────────────

describe('reserved words', () => {

    test('reserved word table gets the_ prefix', () => {
        const out = ddl(`comment\n    text`);
        expect(out).toContain('the_comment');
    });

    test('reserved word table with user prefix does not get the_', () => {
        const out = ddl(`comment\n    text\n# settings = {"prefix":"app"}`);
        expect(out).toContain('app_comment');
        expect(out).not.toContain('the_comment');
    });

    test('comment column is renamed to the_comment', () => {
        const out = ddl(`demo_item_order\n    comment vc80`);
        expect(out).toContain('the_comment');
    });

});

// ── Quoted identifiers & unicode ──────────────────────────────────────────────

describe('quoted identifiers and unicode', () => {

    test('unicode column names are double-quoted', () => {
        const out = ddl(`Bug35842845\n    ファーストネーム vc200\n    Das Gedöns vc200\n    country;shutdown abort;a`);
        expect(out).toContain('"ファーストネーム"');
        expect(out).toContain('"Das Gedöns"');
        expect(out).toContain('"country;shutdown abort;a"');
    });

    test('quoted table name passes through correctly', () => {
        const out = ddl(`"Test"\n    "CamelCase"\n    x   [coMment]\n    2   --coMment2`);
        expect(out).toContain('create table "Test"');
        expect(out).toContain('Test_id_pk');
        expect(out).toContain('"CamelCase"');
        expect(out).toContain('comment on column "Test".x is ');
        expect(out).toContain('comment on column "Test".x2 is ');
    });

    test('unique index name is derived correctly', () => {
        const out = ddl(`t\n    s vc20 /nn /unique\n#prefix: e01`);
        const trimmed = out.substring(0, out.indexOf('-- Generated by Radicle QuickSQL'));
        expect(trimmed).toContain('e01_t_id_pk');
        expect(trimmed).toContain('e01_t_s_unq');
    });

});

// ── REST / flashback ──────────────────────────────────────────────────────────

describe('REST and flashback', () => {

    test('/rest handler references table name in correct order', () => {
        const out = ddl(`mytable /rest\n    name`);
        expect(out.indexOf('p_object') + 5).toBeLessThan(out.indexOf('MYTABLE'));
    });

    test('/rest handler references quoted table name', () => {
        const out = ddl(`"yourTable" /rest\n    name`);
        expect(out.indexOf('p_object') + 5).toBeLessThan(out.lastIndexOf('yourTable'));
    });

    test('/flashback generates ALTER TABLE flashback archive', () => {
        const out = ddl(`departments /flashback\n    name`);
        expect(out).toContain('alter table departments flashback archive;');
    });

    test('/flashback with archive name', () => {
        const out = ddl(`departments /flashback myarchive\n    name`);
        expect(out).toContain('alter table departments flashback archive myarchive;');
    });

    test('/fda alias works same as /flashback', () => {
        expect(ddl(`departments /fda\n    name`)).toContain('alter table departments flashback archive;');
        expect(ddl(`departments /fda myarchive\n    name`)).toContain('alter table departments flashback archive myarchive;');
    });

});

// ── Immutable tables ──────────────────────────────────────────────────────────

describe('immutable tables', () => {

    test('/immutable on db < 23 → trigger-based approach', () => {
        const out = ddl(`inspection_p /immutable\n    finding vc(200)\n    severity vc(20)`);
        expect(out).toContain('before update or delete');
        expect(out).toContain('co_immutable_err');
        expect(out).toContain('raise_application_error(co_immutable_err, co_immutable_msg)');
        expect(out).toContain('trg_inspection_p_insertonly');
        expect(out).toContain('inspection_p is immutable');
    });

    test('regular table has no immutable trigger', () => {
        const out = ddl(`regular_table\n    name`);
        expect(out).not.toContain('insertonly');
        expect(out).not.toContain('raise_application_error');
    });

});

// ── SODA collections ──────────────────────────────────────────────────────────

describe('SODA collections', () => {

    test('/soda generates standard SODA columns', () => {
        const out = ddl(`mycollection /soda`);
        expect(out).toContain('create table mycollection');
        expect(out).toContain('id              varchar2(255 char)');
        expect(out).toContain('mycollection_id_pk primary key');
        expect(out).toContain('created_on      timestamp');
        expect(out).toContain('last_modified   timestamp');
        expect(out).toContain('version         varchar2(255 char)');
        expect(out).toContain('json_document   json');
    });

    test('/soda with semantics:byte uses byte', () => {
        const out = ddl(`mycollection /soda\n# settings = {"semantics":"byte"}`);
        expect(out).toContain('varchar2(255 byte)');
    });

    test('/soda with prefix applies prefix', () => {
        const out = ddl(`docs /soda\n# settings = {"prefix":"app"}`);
        expect(out).toContain('create table app_docs');
        expect(out).toContain('json_document');
    });

    test('/soda collection does not generate BIU trigger', () => {
        const out = ddl(`visit_inspection_c /soda\n# settings = {"pk":"IDENTITY","rowversion":true,"auditcols":"Y","apex":"Y"}`);
        expect(out).not.toContain('visit_inspection_c_biu');
        expect(out).toContain('json_document');
    });

});

// ── Annotations ───────────────────────────────────────────────────────────────

describe('Oracle annotations', () => {

    test('table-level annotation generates ANNOTATIONS clause', () => {
        const out = ddl(`departments {UI_Display 'Departments', Classification 'HR'}\n    name`);
        expect(out).toContain("annotations (UI_Display");
        expect(out).toContain(")\nannotations (");
    });

    test('column-level annotation', () => {
        const out = ddl(`departments\n    name {UI_Display 'Department Name'}`);
        expect(out).toContain("annotations (UI_Display");
        expect(out).toContain("char) annotations (");
    });

    test('flag annotation (no value)', () => {
        const out = ddl(`departments\n    code {SurrogateKey}`);
        expect(out).toContain('annotations (SurrogateKey)');
    });

    test('comment and annotation coexist', () => {
        const out = ddl(`departments [Main table] {Classification 'HR'}\n    name [Full name] {UI_Display 'Name'}`);
        expect(out).toContain('comment on table departments');
        expect(out).toContain('comment on column departments.name');
        expect(out).toContain("annotations (Classification");
        expect(out).toContain("annotations (UI_Display");
    });

    test('multiple annotations on column', () => {
        const out = ddl(`departments\n    name {UI_Display 'Name', Highlight}`);
        expect(out).toContain('Highlight');
        expect(out).toContain('UI_Display');
    });

    test('annotation with /nn', () => {
        const out = ddl(`departments\n    name /nn {Format 'text'}`);
        expect(out).toContain('not null');
        expect(out).toContain("annotations (Format");
    });

    test('annotation does not alter table name', () => {
        const out = ddl(`departments {SomeAnnotation}\n    name`);
        expect(out).toContain('create table departments');
    });

    test('view-level annotation', () => {
        const out = ddl(`dept\n    name\nview dept_v dept {UI_Display 'Department View'}`);
        expect(out).toContain("annotations (ui_display");
        expect(out).toContain('view dept_v');
    });

    test('DESCRIPTION annotation generates comment on table', () => {
        const out = ddl(`departments {DESCRIPTION 'Main HR departments table'}\n    name`);
        expect(out).toContain('comment on table departments');
        expect(out).toContain('Main HR departments table');
        expect(out).toContain("annotations (DESCRIPTION");
    });

    test('DESCRIPTION wins over explicit bracket comment', () => {
        const out = ddl(`departments [Explicit comment] {DESCRIPTION 'Annotation description'}\n    name`);
        expect(out).toContain('comment on table departments');
        expect(out).toContain("is 'Annotation description'");
        expect(out).not.toContain("is 'Explicit comment'");
    });

    test('TGROUP annotation generates group insert statements', () => {
        const out = ddl(`departments {TGROUP 'HR Tables'}\n    name\nemployees {TGROUP 'HR Tables'}\n    name\nprojects {TGROUP 'PM Tables'}\n    name`);
        expect(out).toContain('table groups');
        expect(out).toContain("insert into user_annotations_groups$ (group_name) values ('HR Tables')");
        expect(out).toContain("insert into user_annotations_group_members$ (group_name, object_name) values ('HR Tables', 'DEPARTMENTS')");
        expect(out).toContain("insert into user_annotations_group_members$ (group_name, object_name) values ('HR Tables', 'EMPLOYEES')");
        expect(out).toContain("insert into user_annotations_groups$ (group_name) values ('PM Tables')");
        expect(out).toContain("insert into user_annotations_group_members$ (group_name, object_name) values ('PM Tables', 'PROJECTS')");
        expect(out).toContain("annotations (TGROUP");
    });

});

// ── Oracle 23ai+ features ─────────────────────────────────────────────────────

describe('Oracle 23ai+ features', () => {

    test('boolean native type on db >= 23', () => {
        const out = ddl(`boolvalues\n    is_legal\n    finished_yn\n    ok   bool\n    yes  boolean\n#db:"23"`);
        expect(out).toContain('is_legal       boolean,');
        expect(out).toContain('finished_yn    boolean,');
        expect(out).toContain('ok             boolean,');
        expect(out).toContain('yes            boolean');
    });

    test('boolean native type on db:23c', () => {
        const out = ddl(`boolvalues\n    is_legal\n    finished_yn\n    ok   bool\n    yes  boolean\n#db:"23c"`);
        expect(out).toContain('ok             boolean');
    });

    test('boolean native type on db:26ai', () => {
        const out = ddl(`boolvalues\n    is_legal\n    finished_yn\n    ok   bool\n    yes  boolean\n#db:"26ai"`);
        expect(out).toContain('ok             boolean');
    });

    test('boolean:yn overrides native boolean even on db >= 23', () => {
        const out = ddl(`boolvalues\n    ok   bool\n#boolean:yn\n#db:"26ai"`);
        expect(out).not.toContain('ok    boolean');
    });

    test('boolean:native forces native boolean', () => {
        const out = ddl(`boolvalues\n    ok   bool\n#boolean:native`);
        expect(out).toContain('ok    boolean');
    });

    test('is_active (vc1/check Y,N) maps to boolean true/false on db >= 23', () => {
        const out = ddl(`# settings = {"db":"23ai","pk":"IDENTITY"}\ntenant\n  is_active vc(1) /nn /check Y, N /default Y\n  flag_yn boolean /default N`);
        expect(out).toContain('is_active');
        expect(out).toContain('boolean default on null true');
        expect(out).not.toContain("default on null 'Y'");
        expect(out).not.toContain("in ('Y','N')");
        expect(out).toContain('flag_yn');
        expect(out).toContain('boolean default on null false');
    });

    test('is_active on db < 23 stays varchar2', () => {
        const out = ddl(`# settings = {"db":"19c","pk":"IDENTITY"}\ntenant\n  is_active vc(1) /nn /check Y, N /default Y`);
        expect(out).toContain('varchar2(1');
        expect(out).toContain("default on null 'Y'");
        expect(out).toContain("in ('Y','N')");
    });

    test('json native type on db >= 23', () => {
        const out = ddl(`# settings = {"db":"23ai"}\ntest_json\n    payload json`);
        expect(out).toContain('payload    json');
        expect(out).not.toContain('clob check');
        expect(out).not.toContain('is json');
    });

    test('json stays clob check on db < 23', () => {
        const out = ddl(`# settings = {"db":"19c"}\ntest_json\n    payload json`);
        expect(out).toContain('clob check (payload is json)');
    });

    test('drop:Y on db >= 23 uses DROP TABLE IF EXISTS', () => {
        const out = ddl(`# settings = {"db":"26ai","drop":"Y"}\ntest_drop\n    name`);
        expect(out).toContain('drop table if exists');
    });

    test('drop:Y on db < 23 does not use IF EXISTS', () => {
        const out = ddl(`# settings = {"db":"19c","drop":"Y"}\ntest_drop2\n    name`);
        expect(out).toContain('drop table test_drop2');
        expect(out).not.toContain('if exists');
    });

    test('immutable table on db >= 23 uses CREATE IMMUTABLE TABLE', () => {
        const out = ddl(`# settings = {"db":"23ai"}\naudit_log /immutable\n    finding vc(200)`);
        expect(out).toContain('create immutable table audit_log');
        expect(out).toContain('no drop until 0 days idle');
        expect(out).toContain('no delete until 16 days after insert');
        expect(out).not.toContain('raise_application_error');
        expect(out).not.toContain('insertonly');
    });

    test('immutable table on db < 23 uses trigger-based approach', () => {
        const out = ddl(`# settings = {"db":"19c"}\naudit_log /immutable\n    finding vc(200)`);
        expect(out).not.toContain('create immutable table');
        expect(out).toContain('create table audit_log');
        expect(out).toContain('raise_application_error');
        expect(out).toContain('insertonly');
    });

    test('vector column on db >= 23 gets CREATE VECTOR INDEX', () => {
        const out = ddl(`# settings = {"db":"26ai"}\ndocuments\n    title vc(200)\n    embedding vector`);
        expect(out).toContain('create vector index');
        expect(out).toContain('organization neighbor partitions');
        expect(out).toContain('with distance cosine');
    });

    test('vector column on db < 23 does not get vector index', () => {
        const out = ddl(`# settings = {"db":"19c"}\ndocuments\n    title vc(200)\n    embedding vector`);
        expect(out).not.toContain('create vector index');
    });

    test('compress:Y on db >= 23 uses ROW STORE COMPRESS ADVANCED', () => {
        const out = ddl(`# settings = {"db":"26ai","compress":"Y"}\nbig_table\n    name`);
        expect(out).toContain('row store compress advanced');
        expect(out).not.toContain(') compress;');
    });

    test('compress:Y on db < 23 uses plain ) compress;', () => {
        const out = ddl(`# settings = {"db":"19c","compress":"Y"}\nbig_table2\n    name`);
        expect(out).toContain(') compress;');
        expect(out).not.toContain('row store compress advanced');
    });

    test('audit date type setting (timestamp with time zone)', () => {
        const out = ddl(`# settings = {"auditdate":"timestamp with time zone","auditcols":"Y","apex":"Y"}\ntest_audit\n    name`);
        expect(out).toContain('timestamp with time zone not null');
        expect(out).toContain('systimestamp');
        expect(out).not.toContain(':= sysdate');
    });

    test('JSON relational duality view (db >= 23)', () => {
        const out = ddl(`# settings = {"db":"23ai"}\ndepartments\n    name\n    employees\n        first_name\n        last_name\n        salary num\n\ndv dept_emp_dv departments employees`);
        expect(out).toContain('create or replace json relational duality view');
        expect(out).toContain('dept_emp_dv');
        expect(out).toContain('@insert @update @delete');
        expect(out).toContain('[{');
        expect(out).toContain('first_name');
        expect(out).toContain('last_name');
    });

});

// ── AI enrichment (metadata_annotations) ─────────────────────────────────────

describe('AI enrichment (metadata_annotations)', () => {

    test('table annotations call metadata_annotations.set() on db >= 26', () => {
        const out = ddl(`departments {Classification 'HR', UI_Display 'Departments'}\n    name`, '{"db":"26ai", "aienrichment":"yes"}');
        expect(out).toContain('AI enrichment');
        expect(out).toContain("metadata_annotations.set('Classification', 'HR', 'DEPARTMENTS')");
        expect(out).toContain("metadata_annotations.set('UI_Display', 'Departments', 'DEPARTMENTS')");
    });

    test('column annotations use TABLE COLUMN type', () => {
        const out = ddl(`departments\n    name {UI_Display 'Department Name'}`, '{"db":"26ai", "aienrichment":"yes"}');
        expect(out).toContain("metadata_annotations.set('UI_Display', 'Department Name', 'DEPARTMENTS.NAME', 'TABLE COLUMN')");
    });

    test('view annotations use VIEW type', () => {
        const out = ddl(`departments\n    name\nview dept_v departments {UI_Display 'Department View'}`, '{"db":"26ai", "aienrichment":"yes"}');
        expect(out).toContain("metadata_annotations.set('UI_Display', 'Department View', 'DEPT_V', 'VIEW')");
    });

    test('TGROUP annotations use create_group() / add_to_group()', () => {
        const out = ddl(`departments {TGROUP 'HR Tables'}\n    name\nemployees {TGROUP 'HR Tables'}\n    name`, '{"db":"26ai", "aienrichment":"yes"}');
        expect(out).toContain("metadata_annotations.create_group('HR Tables')");
        expect(out).toContain("metadata_annotations.add_to_group('HR Tables', 'DEPARTMENTS', 'TABLE')");
        expect(out).toContain("metadata_annotations.add_to_group('HR Tables', 'EMPLOYEES', 'TABLE')");
    });

    test('no enrichment when db < 26', () => {
        const out = ddl(`departments {Classification 'HR'}\n    name`, '{"db":"23ai", "aienrichment":"yes"}');
        expect(out).not.toContain('metadata_annotations');
    });

    test('no enrichment when aienrichment not enabled', () => {
        const out = ddl(`departments {Classification 'HR'}\n    name`, '{"db":"26ai"}');
        expect(out).not.toContain('metadata_annotations');
    });

    test('flag annotations (no value) are skipped in enrichment', () => {
        const out = ddl(`departments {SurrogateKey}\n    name`, '{"db":"26ai", "aienrichment":"yes"}');
        expect(out).not.toContain('metadata_annotations');
    });

    test('prefix applied to object name in enrichment', () => {
        const out = ddl(`departments {Classification 'HR'}\n    name`, '{"db":"26ai", "aienrichment":"yes", "prefix":"APP"}');
        expect(out).toContain("metadata_annotations.set('Classification', 'HR', 'APP_DEPARTMENTS')");
    });

});

// ── Translation (/trans directive) ───────────────────────────────────────────

describe('translation (/trans)', () => {

    test('/trans generates language table + _trans table + _resolved view', () => {
        const out = ddl(`knowledge_type\n    knowledge_type vc(1024) /nn /trans\n    display_order number`);
        expect(out).toContain('create table language');
        expect(out).toContain('language_code_pk primary key');
        expect(out).toContain('create table knowledge_type_trans');
        expect(out).toContain('knowledge_type_id');
        expect(out).toContain('language_code');
        expect(out).toContain('trans_knowledge_type');
        expect(out).toContain('knowledge_type_trans_uk unique');
        expect(out).toContain('knowledge_type_trans_lang_fk');
        expect(out).toContain('create or replace view knowledge_type_resolved');
        expect(out).toContain('coalesce(t.trans_knowledge_type, k.knowledge_type)');
        expect(out).toContain('k.display_order');
        expect(out).toContain("sys_context('APP_CTX','LANG')");
    });

    test('/trans on clob column preserves clob type in _trans table', () => {
        const out = ddl(`articles\n    title vc(200) /trans\n    body clob /trans\n    status vc(20)`);
        expect(out).toContain('trans_title');
        expect(out).toContain('trans_body');
        expect(out).toContain('clob');
        expect(out).toContain('create or replace view articles_resolved');
        expect(out).toContain('coalesce(t.trans_title, k.title)');
        expect(out).toContain('coalesce(t.trans_body, k.body)');
        expect(out).toContain('k.status');
    });

    test('/translation and /translations aliases work', () => {
        const out = ddl(`products\n    product_name vc(200) /translation\n    description vc(4000) /translations`);
        expect(out).toContain('create table products_trans');
        expect(out).toContain('trans_product_name');
        expect(out).toContain('trans_description');
    });

    test('custom transcontext setting', () => {
        const out = ddl(`items\n    item_name vc(100) /trans\n# transcontext: "sys_context('MY_CTX','LANGUAGE')"`);
        expect(out).toContain("sys_context('MY_CTX','LANGUAGE')");
    });

    test('no /trans → no language table or _trans/_resolved', () => {
        const out = ddl(`simple_table\n    name\n    description`);
        expect(out).not.toContain('create table language');
        expect(out).not.toContain('_trans');
        expect(out).not.toContain('_resolved');
    });

    test('view over table with /trans uses LEFT JOIN + coalesce', () => {
        const out = ddl(`locations\n    name vc(200) /trans\n    code vc(10)\n    tenant_id\n\nview location_v locations`);
        expect(out).toContain('coalesce(t_locations.trans_name, locations.name)');
        expect(out).toContain('left join locations_trans t_locations');
        expect(out).toContain("sys_context('APP_CTX','LANG')");
        expect(out).toContain('locations.tenant_id');
        expect(out).toContain('locations.code');
    });

    test('column name inference by naming pattern', () => {
        const out = ddl(`test\n    test_name\n    test_description\n    test_number\n    test_date`);
        expect(out).toContain('test_name           varchar2(255');
        expect(out).toContain('test_description    varchar2(4000');
        expect(out).toContain('test_number         number');
        expect(out).toContain('test_date           date');
    });

});
